import type { Pathway } from "./types";

export const pathways: Pathway[] = [
  {
    id: "vision",
    title: "Vision",
    short: "Vision",
    subtitle: "From the eye to visual cortex and beyond",
    color: "#77e8db",
    icon: "vision",
    intro:
      "The main visual pathway runs from the retina to the thalamus (LGN) and then to primary visual cortex (V1). From V1, two streams carry the signal onward: one into the temporal lobe, which identifies objects, and one into the parietal lobe, which locates them and guides movement.",
    insight:
      "The retina splits the image into parallel channels before it leaves the eye, and the LGN keeps them separate. At the chiasm, fibres are regrouped so that each hemisphere receives the opposite half of the visual field. V1 represents the visual field as local features such as edges. Beyond V1, the ventral stream identifies objects, with regions that prefer faces, places, bodies and words, and the dorsal stream processes motion and location to guide action.",
    caveat:
      "Both eyes connect to the chiasm; after that, the animation follows the route in the left hemisphere, which receives the right half of the visual field. Nerves, tracts and cortical routes are drawn as single curves; the real connections are many parallel fibre bundles that run in both directions, and the two streams exchange information at many points. Routes to the superior colliculus and pretectum are not shown. MT, IT and the category-selective areas are markers at typical positions from group studies; their positions vary by several millimetres between people, and the face area is usually larger in the right hemisphere. The V1 highlight follows the calcarine sulcus; the actual border varies between people.",
    steps: [
      {
        key: "light-to-signals",
        region: "retina",
        title: "Light becomes neural signals",
        body: "Rods (dim light) and cones (colour and detail) absorb light. In photoreceptors, light reduces electrical activity. Retinal circuits compare neighbouring points, so the output mainly reports contrast and change. Ganglion cells send this output through the optic nerve. Different types of ganglion cell carry different information: midget cells carry fine detail and red–green colour; parasol cells carry motion and changes in brightness.",
        fact: "About 96 million photoreceptors connect to roughly 1 million ganglion cells, so the signal is compressed around 100-fold before it leaves the eye.",
        signal: [],
      },
      {
        key: "optic-chiasm",
        region: "chiasm",
        title: "Fibres cross at the optic chiasm",
        body: "The two optic nerves meet under the brain. Fibres from the half of each retina nearest the nose cross to the other side; fibres from the outer half do not. After this point, each hemisphere receives the opposite half of the visual field from both eyes.",
        fact: "About half of the fibres cross (commonly cited as 53%, from a single detailed count). This is why damage behind the chiasm affects the same half of the visual field in both eyes.",
      },
      {
        key: "parallel-channels",
        region: "lgn",
        title: "Parallel channels in the LGN",
        body: "Most optic tract fibres end in the [[lgn|lateral geniculate nucleus]] (LGN) of the thalamus. Its layers keep the two eyes separate and keep three channels apart. Magnocellular layers receive parasol cells: fast signals about motion and coarse shape. Parvocellular layers receive midget cells: slower signals about fine detail and red–green colour. Thin koniocellular layers carry blue–yellow colour. The LGN also receives more input from the cortex than from the eyes.",
        fact: "In monkeys, about 80% of retinal ganglion cells feed the parvocellular layers and about 10% the magnocellular layers. The fastest magnocellular responses arrive about 10 ms before the fastest parvocellular ones.",
      },
      {
        key: "primary-visual-cortex",
        region: "v1",
        title: "Primary visual cortex (V1)",
        body: "The optic radiation carries LGN output to [[v1|primary visual cortex]] at the back of the brain. V1 contains a map of the visual field in which neighbouring points stay next to each other, and the centre of gaze takes up much more cortex than the periphery. Many V1 neurons respond best to edges at a specific orientation. V1 sends its output to many [[extrastriate|higher visual areas]].",
        fact: "The map is inverted: the upper visual field is represented below the calcarine sulcus and the lower field above it.",
      },
      {
        key: "two-streams",
        region: "extrastriate",
        title: "Two streams leave V1",
        body: "From V1, visual information travels along two main routes. The ventral stream runs down into the temporal lobe through areas V2 and V4 and identifies what things are. The dorsal stream runs up into the parietal lobe through [[mt|area MT]] and represents where things are and how to act on them. The dorsal stream receives mostly magnocellular input; the ventral stream receives both channels. The two streams exchange information at many points.",
        fact: "A patient known as D.F., with damage to her ventral stream, could not report how a slot was oriented, yet could post a card through it accurately. Her dorsal stream still guided the movement.",
        signal: [
          [
            ["v1", "extrastriate"],
            ["v1", "mt"],
          ],
        ],
      },
      {
        key: "motion",
        region: "mt",
        title: "Motion in area MT",
        body: "[[mt|Area MT]] (also called V5) is specialized for motion. Most of its neurons respond to movement in a particular direction and at a particular speed. In monkeys, electrically stimulating a small group of MT neurons shifts the animal's judgement of motion toward those neurons' preferred direction. A neighbouring area, MST, responds to the overall pattern of motion produced when you move through a scene (optic flow).",
        fact: "A patient with damage to this region on both sides lost most of her perception of motion. Pouring tea was difficult because the liquid appeared frozen.",
        signal: [[["v1", "mt"]]],
      },
      {
        key: "location-and-action",
        region: "parietal",
        title: "Location and action in parietal cortex",
        body: "The dorsal stream continues from MT to [[parietal|posterior parietal cortex]]. Here, the position of things in view is combined with the position of the eyes, head and hand, so that vision can guide eye movements, reaching and grasping. The same region helps direct attention to locations (see the Attention topic).",
        fact: "Damage here can cause optic ataxia: a person can see and describe an object but reaches for it inaccurately.",
        signal: [[["mt", "parietal"]]],
      },
      {
        key: "object-recognition",
        region: "it",
        title: "Object recognition in inferior temporal cortex",
        body: "The ventral stream runs from V1 through V2 and V4 to [[it|inferior temporal cortex]] (IT). Along the way, neurons respond to increasingly complex features: edges in V1, contours and simple shapes in V2 and V4, and objects and object parts in IT. IT responses stay similar when an object moves, changes size or is seen from a somewhat different angle.",
        fact: "In monkeys, the activity of about 100 IT neurons over as little as 12.5 ms was enough to tell which object was shown and its category, even when its position and size changed.",
        signal: [[["v1", "extrastriate"]], [["extrastriate", "it"]]],
      },
      {
        key: "category-areas",
        region: "ffa",
        title: "Areas for faces, places, bodies and words",
        body: "Some regions of temporal cortex respond more strongly to one category of image than to others. The [[ffa|fusiform face area]] prefers faces, the [[ppa|parahippocampal place area]] prefers places and scenes, the [[eba|extrastriate body area]] prefers bodies and body parts, and the [[vwfa|visual word form area]] prefers written words. Each responds most to its category but also responds to others, and the surrounding cortex carries category information too.",
        fact: "When a patient's fusiform face area was electrically stimulated, the faces of people in the room appeared distorted, while other objects looked normal.",
        signal: [
          [
            ["extrastriate", "ffa"],
            ["extrastriate", "ppa"],
            ["extrastriate", "eba"],
            ["extrastriate", "vwfa"],
          ],
        ],
      },
    ],
    edges: [
      {
        from: "retina",
        to: "chiasm",
        bend: [-0.1, -0.08, 0],
        stage: 0,
      },
      {
        from: "retinaR",
        to: "chiasm",
        bend: [-0.1, -0.08, 0],
        stage: 0,
      },
      {
        from: "chiasm",
        to: "lgn",
        bend: [0.06, -0.06, 0.03],
        stage: 1,
      },
      {
        from: "lgn",
        to: "v1",
        bend: [0.1, -0.18, 0.32],
        stage: 2,
      },
      {
        from: "v1",
        to: "extrastriate",
        bend: [0.12, 0, 0],
        detail: true,
      },
      {
        from: "v1",
        to: "mt",
        bend: [0.15, 0.05, 0.05],
        detail: true,
      },
      {
        from: "mt",
        to: "parietal",
        bend: [0.1, 0, 0.2],
        detail: true,
      },
      {
        from: "extrastriate",
        to: "it",
        bend: [0, -0.15, 0.2],
        detail: true,
      },
      {
        from: "extrastriate",
        to: "ffa",
        bend: [0, -0.18, 0],
        kind: "branch",
        detail: true,
      },
      {
        from: "extrastriate",
        to: "ppa",
        bend: [0, -0.2, -0.05],
        kind: "branch",
        detail: true,
      },
      {
        from: "extrastriate",
        to: "eba",
        bend: [0, 0, 0.15],
        kind: "branch",
        detail: true,
      },
      {
        from: "extrastriate",
        to: "vwfa",
        bend: [0, -0.12, 0.08],
        kind: "branch",
        detail: true,
      },
    ],
    sourceIds: [
      "visual",
      "visual-anatomy",
      "photoreceptors",
      "hubel-wiesel",
      "parallel-pathways",
      "two-streams",
      "mt-review",
      "object-recognition",
      "vtc-review",
    ],
  },
  {
    id: "touch",
    title: "Touch",
    short: "Touch",
    subtitle: "Touch, position, pain and temperature, from the body to cortex",
    color: "#89bdf4",
    icon: "touch",
    intro:
      "Signals from the body reach the brain by two main routes. Fine touch, vibration and body position run up the dorsal columns of the spinal cord and cross to the other side in the medulla. Pain, temperature and itch cross in the spinal cord, near where they enter, and run up the spinothalamic tract. Both routes pass through the thalamus to the cortex, so each hemisphere receives signals from the opposite side of the body.",
    insight:
      "The two routes cross at different levels, so damage to one half of the spinal cord affects fine touch on one side of the body and pain on the other. The touch route leads to S1, which maps the body surface in detail, and on to parietal cortex, which uses touch to guide action. The pain and temperature route reaches S1 and S2, and also the posterior insula, which represents the body’s internal condition, and the cingulate cortex, whose activity follows how unpleasant pain feels. Whether any cortical area responds to pain alone is debated.",
    caveat:
      "The routes shown run from the right side of the body to the left hemisphere. The spinal cord is not part of the model: the dorsal horn marker sits at the lower end of the medulla and stands for every level of the cord. Skin receptors and individual nuclei are not drawn; the medulla and thalamus highlights show the larger structures that contain them. Spinothalamic fibres end in several thalamic nuclei, which share one thalamus marker here, and all routes are drawn as single curves. S2 and the posterior insula are markers at typical positions from group studies; S2 is active in both hemispheres. Position sense from the legs partly uses a different spinal route, and the face uses the trigeminal nerve and the VPM.",
    steps: [
      {
        key: "dorsal-columns",
        region: "medulla",
        title: "Touch and position: up the dorsal columns",
        body: "Receptors in the skin, muscles and joints respond to pressure, vibration and stretch. Their large, fast nerve fibres enter the spinal cord and travel up the same side in the dorsal columns. In the lower medulla they connect to the [[medulla|dorsal column nuclei]], whose fibres then cross to the other side and form the medial lemniscus.",
        fact: "Touch fibres from the skin conduct at about 35–75 metres per second. The thin C fibres that carry slow, burning pain conduct at about 0.4–1.4 metres per second.",
        signal: [],
      },
      {
        key: "vpl-relay",
        region: "vpl",
        title: "Relay in the VPL",
        body: "The crossed fibres travel in the medial lemniscus to the [[vpl|ventral posterolateral nucleus]] (VPL) of the thalamus. The VPL is the thalamic relay for touch and body position from the body, as the LGN is for vision and the MGN for hearing. It contains a map of the opposite side of the body and also receives part of the pain and temperature pathway, described in later steps. Touch from the face uses a neighbouring nucleus, the VPM.",
        fact: "Because of the crossing, the right hand is represented in the left thalamus and left cortex.",
      },
      {
        key: "primary-somatosensory-cortex",
        region: "s1",
        title: "Primary somatosensory cortex (S1)",
        body: "[[s1|Primary somatosensory cortex]] runs along the postcentral gyrus and contains a map of the opposite side of the body, with the foot near the midline and the face and tongue at the lower end. The hands, lips and tongue take up much more of this map than the back or legs. S1 is made of four narrow strips, areas 3a, 3b, 1 and 2, each with its own body map. In monkeys, area 3a responds mainly to muscle stretch and joint movement, areas 3b and 1 mainly to touch on the skin, and area 2 to both, with larger receptive fields and some neurons tuned to object shape. Most neurons combine several types of input.",
        fact: "Wilder Penfield mapped this area by electrically stimulating the cortex of awake patients during epilepsy surgery; patients reported sensations in specific body parts.",
      },
      {
        key: "posterior-parietal",
        region: "parietal",
        title: "Posterior parietal cortex",
        body: "[[parietal|Posterior parietal cortex]] combines touch with vision and body position to track where objects are relative to the body. This information is used for actions such as reaching and grasping.",
        fact: "Damage to parietal cortex, usually on the right, can cause neglect: the person does not attend to one side of space, sometimes including their own body. The damage that causes it usually lies in the inferior parietal lobule or the nearby temporoparietal junction, below the area highlighted here.",
      },
      {
        key: "secondary-somatosensory-cortex",
        region: "s2",
        title: "Secondary somatosensory cortex (S2)",
        body: "[[s2|Secondary somatosensory cortex]] lies on the parietal operculum, the upper bank of the lateral sulcus, just below the lower end of S1. It receives input from all four areas of S1 and directly from the thalamus. In monkeys, its neurons respond to touch over larger areas of skin than S1 neurons, often on both hands. In human brain imaging, touch on the right hand activates S2 in both hemispheres. S2 also responds to painful stimuli, and briefly disrupting it with magnetic stimulation made people worse at judging how intense a pain was.",
        fact: "In macaques, removing the part of S1 that represents one body part left the matching part of S2 unresponsive to touch, while removing S2 left S1 responses unchanged.",
        signal: [[["s1", "s2"]]],
      },
      {
        key: "pain-crossing",
        region: "dorsalHorn",
        title: "Pain and temperature cross in the spinal cord",
        body: "Pain, temperature and itch are detected by free nerve endings with thin fibres. Thinly myelinated Aδ fibres carry the first, sharp pain; the slower, burning pain that follows comes mainly from unmyelinated C fibres. These fibres end in the [[dorsalHorn|dorsal horn]] of the spinal cord. Neurons there send their axons across to the other side of the cord, close to the level where the signal entered, and up the spinothalamic tract to the thalamus. Touch and position fibres stay on the same side until the medulla, so damage to one half of the spinal cord removes fine touch on the same side of the body and pain and temperature on the opposite side.",
        fact: "Surgeons can relieve severe one-sided cancer pain by cutting this tract high in the neck, on the side opposite the pain. In a study of 19 such patients, pain, temperature and itch on the painful side were lost or greatly reduced, while the threshold for detecting light touch did not change.",
        signal: [],
      },
      {
        key: "posterior-insula",
        region: "postInsula",
        title: "Posterior insula: pain, temperature and the body’s condition",
        body: "Spinothalamic fibres end in several thalamic nuclei. Some end in the VPL, which projects to S1; others end in posterior and medial nuclei that project to S2, the [[postInsula|posterior insula]] and the [[cingulate|cingulate cortex]]. The posterior insula, deep in the lateral sulcus, responds to painful heat and to cooling, with a rough map of the body. Craig proposed that it is the primary cortical area for interoception, the sense of the body’s internal condition, and that it passes this information forward to the [[insula|anterior insula]]. He also described a separate thalamic nucleus (VMpo) that relays pain and temperature to it; other anatomists argue that this region is part of neighbouring nuclei.",
        fact: "Among 4,160 electrical stimulations of the cortex in 164 patients being assessed for epilepsy surgery, only 1.4% evoked pain, all in the posterior insula and the neighbouring parietal operculum. Stimulating S1 or the cingulate cortex never did.",
        signal: [
          [["dorsalHorn", "vpl"]],
          [
            ["vpl", "s1"],
            ["vpl", "s2"],
            ["vpl", "postInsula"],
          ],
        ],
      },
      {
        key: "pain-unpleasantness",
        region: "cingulate",
        title: "Cingulate cortex: how unpleasant pain feels",
        body: "Pain has a sensory side, where it is and how strong it is, and an emotional side, how unpleasant it is. Spinothalamic signals reach the [[cingulate|anterior cingulate cortex]] through nuclei in the middle of the thalamus, and activity here follows how unpleasant a painful stimulus feels. Much of the response to brief painful stimuli in the cingulate cortex, insula and S2 also appears with other sudden stimuli, such as touches, sounds or flashes, which links these areas to the salience network (see the Attention topic). Whether any cortical area responds to pain alone is debated.",
        fact: "When hypnotic suggestions made a painful stimulus feel more or less unpleasant without changing how intense it felt, activity changed in the anterior cingulate cortex but not in S1.",
        signal: [[["vpl", "cingulate"]]],
      },
    ],
    edges: [
      {
        from: "medulla",
        to: "vpl",
        bend: [0.07, 0.09, 0],
        stage: 0,
      },
      {
        from: "vpl",
        to: "s1",
        bend: [-0.03, 0.09, 0.15],
        stage: 1,
      },
      {
        from: "s1",
        to: "parietal",
        bend: [0.02, 0.08, 0.08],
        stage: 2,
      },
      {
        from: "s1",
        to: "s2",
        bend: [0, 0, 0],
        detail: true,
      },
      {
        from: "vpl",
        to: "s2",
        bend: [0, 0, 0],
        kind: "branch",
        detail: true,
      },
      {
        from: "dorsalHorn",
        to: "vpl",
        bend: [0, 0, 0],
        detail: true,
      },
      {
        from: "vpl",
        to: "postInsula",
        bend: [0, 0, 0],
        detail: true,
      },
      {
        from: "vpl",
        to: "cingulate",
        bend: [0, 0, 0],
        kind: "branch",
        detail: true,
      },
      {
        from: "postInsula",
        to: "insula",
        bend: [0, 0, 0],
        kind: "branch",
        detail: true,
      },
    ],
    sourceIds: [
      "body-sensation",
      "somatosensory-cortex",
      "pain-pathways",
      "s1-s2-review",
      "s2-bilateral",
      "interoception",
      "cordotomy",
      "pain-stimulation",
      "pain-affect",
      "pain-matrix",
    ],
  },
  {
    id: "hearing",
    title: "Hearing",
    short: "Hearing",
    subtitle: "From the ear to auditory cortex, and back to the ear",
    color: "#ed9bcc",
    icon: "hearing",
    intro:
      "Sound is converted into nerve signals in the cochlea and sorted by frequency. Several brainstem relays process the signal, including comparing the two ears to locate the sound, before it reaches the thalamus (MGN) and primary auditory cortex. Surrounding belt and parabelt areas then process more complex sounds and send signals along two streams, one for identifying sounds and one for locating them. The brain also sends signals back down to the ear.",
    insight:
      "The auditory brainstem processes timing very precisely, which is needed to locate sounds. The frequency map set up in the cochlea (tonotopy) is kept at each stage up to the cortex. In the cortex, processing runs from core to belt to parabelt, with neurons preferring increasingly complex sounds; a stream toward the front of the temporal lobe helps identify sounds, and a stream toward parietal cortex helps locate them. Olivocochlear fibres from the brainstem turn down the cochlea’s amplification, and the cortex can act on them.",
    caveat:
      "The main ascending routes are shown on both sides. The belt, the two streams and the descending route are drawn only from the left hemisphere; they exist on both sides, and locating sounds often relies more on the right hemisphere. The cochlea, auditory nerve, cochlear nuclei, inferior colliculi and geniculate bodies use atlas geometry; the superior olives are approximate positions inside the pons. The atlas does not segment the belt or the anterior superior temporal gyrus; their markers are typical positions from group studies. The “where” route ends at the parietal marker used by other topics (superior parietal lobule); in human studies, locating sounds mainly activates the inferior parietal lobule, just below it. The descending route is drawn through the inferior colliculus; auditory cortex also projects directly to the superior olive (shown in rats). Lateral olivocochlear fibres, the lateral lemniscus and routes that bypass the superior olive are not shown. Routes are drawn as curves, not traced fibres.",
    steps: [
      {
        key: "frequency-sorting",
        region: "cochlea",
        title: "Sound is sorted by frequency",
        body: "In the [[cochlea|cochlea]], the basilar membrane vibrates at different points for different frequencies: high frequencies near the base, low frequencies near the tip. Inner hair cells convert this movement into nerve signals. Outer hair cells change length to amplify quiet sounds and sharpen frequency tuning.",
        fact: "Each cochlea has about 3,500 inner hair cells, and 90–95% of auditory nerve fibres connect to them. In humans, hair cells that are lost do not regrow.",
        signal: [],
      },
      {
        key: "cochlear-nuclei",
        region: "brainstem",
        title: "Cochlear nuclei",
        body: "Each auditory nerve ends in the [[brainstem|cochlear nuclei]] on the same side of the brainstem. Different cell types here extract different features, such as precise timing, loudness and frequency content, and send them along separate pathways.",
        fact: "Input from the two ears first comes together at the next stage, the superior olive. From there on, both hemispheres receive input from both ears.",
      },
      {
        key: "comparing-ears",
        region: "soc",
        title: "Comparing the two ears",
        body: "The [[soc|superior olivary complex]] is the first place where input from both ears is combined. The medial superior olive compares arrival times; the lateral superior olive compares loudness, which differs between the ears because the head blocks some of the sound. These differences are used to locate a sound horizontally.",
        fact: "People can detect arrival-time differences between the ears as small as about 10 microseconds (0.01 milliseconds).",
      },
      {
        key: "inferior-colliculus",
        region: "ic",
        title: "Inferior colliculus",
        body: "Nearly all ascending auditory pathways synapse in the [[ic|inferior colliculus]] in the midbrain. It combines timing, loudness and frequency information and sends signals to the superior colliculus, which helps turn the eyes and head toward a sound.",
        fact: "Because almost all ascending auditory signals pass through it, the inferior colliculus is described as a near-obligatory relay.",
      },
      {
        key: "mgn-relay",
        region: "mgn",
        title: "Relay in the MGN",
        body: "The [[mgn|medial geniculate nucleus]] (MGN) is the auditory relay of the thalamus. Its ventral part keeps the frequency map and projects to primary auditory cortex. Its other parts project to surrounding auditory areas and to the amygdala.",
        fact: "Like the LGN, the MGN receives large feedback projections from the cortex it sends to.",
      },
      {
        key: "primary-auditory-cortex",
        region: "a1",
        title: "Primary auditory cortex (A1)",
        body: "[[a1|Primary auditory cortex]] is on Heschl’s gyrus, inside the lateral sulcus. It is part of the auditory core, the first stage of auditory cortex, which receives its main input from the ventral part of the [[mgn|MGN]]. In humans, the core covers roughly the inner two-thirds of Heschl’s gyrus. Like the cochlea, it is organized by frequency (tonotopy), and pure tones activate it strongly.",
        fact: "Because pathways cross at several levels, each hemisphere receives input from both ears. Damage to auditory cortex on one side rarely causes deafness in one ear.",
      },
      {
        key: "belt-and-parabelt",
        region: "belt",
        title: "Belt and parabelt",
        body: "Around the core lies a ring of [[belt|belt areas]], and just outside the belt, on the superior temporal gyrus, the parabelt. In monkeys, the core feeds eight proposed belt areas, and the belt feeds a parabelt with at least two divisions, giving three stages of processing. Belt neurons respond more to complex sounds, such as bands of noise and frequency sweeps, than to pure tones, and many prefer particular monkey calls. Human brain imaging shows a similar order: pure tones activate mainly the core, noise bands the cortex around it, and vowel sounds areas further forward and outward on the superior temporal gyrus. The stages also work in parallel: belt areas receive some input directly from the thalamus, and in human recordings the superior temporal gyrus responds to speech as early as primary auditory cortex (see the Speech topic).",
        fact: "In monkeys, tracer injected into the parabelt labelled few neurons in the core but many in the belt, evidence that the parabelt receives core output mainly by way of the belt.",
      },
      {
        key: "two-streams",
        region: "astg",
        title: "Two streams leave auditory cortex",
        body: "In monkeys, neurons in the front part of the belt are more selective for the type of call, and neurons in the back part are more selective for where the sound comes from. The front part connects forward along the [[astg|superior temporal gyrus]] and to [[vlpfc|ventrolateral prefrontal cortex]], a proposed “what” stream for identifying sounds. The back part connects with [[parietal|posterior parietal cortex]] and dorsolateral prefrontal cortex, a proposed “where” stream for locating them. Human imaging and brain-damage studies support a similar division. Researchers disagree about how to describe the back route, because it is also used for speech and for linking sounds to movements (see the Speech topic).",
        fact: "Among 15 patients with damage to the right hemisphere, four recognized sounds normally but could not locate them, and three located sounds well but had difficulty recognizing them.",
        signal: [
          [
            ["belt", "astg"],
            ["belt", "parietal"],
          ],
          [["astg", "vlpfc"]],
        ],
      },
      {
        key: "feedback-to-ear",
        region: "soc",
        title: "Feedback to the ear",
        body: "The brain also sends signals back to the ear. Medial olivocochlear neurons in the [[soc|superior olivary complex]] send fibres to the [[cochlea|cochleae]], mostly to the ear on the opposite side, where they end on outer hair cells and reduce their amplification of quiet and moderate sounds. Sound in either ear activates them as a reflex; in animals, this helps the auditory nerve signal brief sounds in background noise and protects the ear from loud noise. [[a1|Auditory cortex]] sends fibres to the [[ic|inferior colliculus]] and, in rats, directly to these olive neurons, and in chinchillas stimulating auditory cortex changes how the cochlea responds. Whether this system helps people understand speech in noise, and how much attention changes the human cochlea, is still debated.",
        fact: "In chinchillas paying attention to lights, auditory nerve responses to ignored clicks fell by up to 4 dB. In people, one study measured sounds emitted by the ear: they were 5.4 dB weaker during visual attention in 15 listeners, with no effect in the next 15.",
        signal: [
          [["a1", "ic"]],
          [["ic", "soc"]],
          [
            ["soc", "cochleaR"],
            ["soc", "cochlea"],
          ],
        ],
      },
    ],
    edges: [
      {
        from: "cochlea",
        to: "brainstem",
        bend: [-0.015, 0.012, 0],
        stage: 0,
      },
      {
        from: "cochleaR",
        to: "brainstemR",
        bend: [-0.015, 0.012, 0],
        stage: 0,
      },
      {
        from: "brainstem",
        to: "soc",
        bend: [-0.04, -0.03, 0],
        stage: 1,
      },
      {
        from: "brainstem",
        to: "socR",
        bend: [-0.045, -0.05, 0],
        stage: 1,
        kind: "branch",
      },
      {
        from: "brainstemR",
        to: "socR",
        bend: [-0.04, -0.03, 0],
        stage: 1,
      },
      {
        from: "brainstemR",
        to: "soc",
        bend: [-0.045, -0.05, 0],
        stage: 1,
        kind: "branch",
      },
      {
        from: "soc",
        to: "ic",
        bend: [0.09, 0, 0.05],
        stage: 2,
      },
      {
        from: "socR",
        to: "icR",
        bend: [0.09, 0, -0.05],
        stage: 2,
      },
      {
        from: "ic",
        to: "mgn",
        bend: [0.02, 0.025, 0.025],
        stage: 3,
      },
      {
        from: "icR",
        to: "mgnR",
        bend: [0.02, 0.025, -0.025],
        stage: 3,
      },
      {
        from: "mgn",
        to: "a1",
        bend: [-0.015, 0.07, 0.015],
        stage: 4,
      },
      {
        from: "mgnR",
        to: "a1R",
        bend: [-0.015, 0.07, -0.015],
        stage: 4,
      },
      {
        from: "a1",
        to: "belt",
        bend: [0, 0, 0],
        detail: true,
      },
      {
        from: "belt",
        to: "astg",
        bend: [0, 0, 0],
        detail: true,
      },
      {
        from: "astg",
        to: "vlpfc",
        bend: [0, 0, 0],
        detail: true,
      },
      {
        from: "belt",
        to: "parietal",
        bend: [0, 0, 0],
        detail: true,
      },
      {
        from: "a1",
        to: "ic",
        bend: [0, 0, 0],
        kind: "feedback",
        detail: true,
      },
      {
        from: "ic",
        to: "soc",
        bend: [0, 0, 0],
        kind: "feedback",
        detail: true,
      },
      {
        from: "soc",
        to: "cochleaR",
        bend: [0, 0, 0],
        kind: "inhibitory",
        detail: true,
      },
      {
        from: "soc",
        to: "cochlea",
        bend: [0, 0, 0],
        kind: "inhibitory",
        detail: true,
      },
    ],
    sourceIds: [
      "ear-anatomy",
      "hair-cells",
      "auditory",
      "auditory-cortex-streams",
      "auditory-what-where",
      "auditory-streams-review",
      "olivocochlear",
      "olivocochlear-behaviour",
      "attention-cochlea",
    ],
  },
  {
    id: "speech",
    title: "Speech and language",
    short: "Speech",
    subtitle: "Hearing and producing speech",
    color: "#f8a47f",
    icon: "speech",
    intro:
      "Speech processing uses two connected streams. The ventral stream, in both hemispheres, maps speech sounds to meaning. The dorsal stream, mainly in the left hemisphere, maps speech sounds to the movements needed to produce them. Repeating a new word uses both.",
    insight:
      "Language depends on a network of regions, mostly in the left hemisphere, while word meaning is represented across both hemispheres. Speech also uses memory, attention and motor systems.",
    caveat:
      "A simplified version of the dual-stream model. Only left-hemisphere regions are drawn, although early speech processing happens in both hemispheres. Area Spt and Broca’s area are placed where they are usually found; their borders vary. The order of steps follows repeating a word; in normal speech these regions are active at the same time and exchange signals in both directions.",
    steps: [
      {
        key: "hearing-speech",
        region: "a1",
        title: "Hearing speech",
        body: "Speech first reaches [[a1|auditory cortex]] like any other sound. Recordings from the brain surface show that the nearby [[temporal|superior temporal gyrus]] receives speech input at the same time as primary auditory cortex, not after it.",
        fact: "In one study, stimulating primary auditory cortex caused sound hallucinations but did not affect word perception, while stimulating the superior temporal gyrus disrupted it. Surgical removal of primary auditory cortex did not impair speech perception.",
        signal: [],
      },
      {
        key: "speech-sounds",
        region: "temporal",
        title: "Recognizing speech sounds",
        body: "Neurons in the [[temporal|superior temporal gyrus]] respond to features of speech sounds, such as whether a consonant is made with the lips or the tongue. From here, the ventral stream links sounds to [[meaning|meaning]] in both hemispheres.",
        fact: "When two people speak at once, activity here mainly follows the speaker being attended to, clearly enough to identify which one.",
        signal: [[["a1", "temporal"]], [["temporal", "meaning"]]],
      },
      {
        key: "sound-to-movement",
        region: "spt",
        title: "Linking sound and movement",
        body: "[[spt|Area Spt]], at the back end of the Sylvian fissure, links the sound of a word to the movements needed to say it. It responds both when hearing speech and when silently rehearsing it.",
        fact: "Damage along this dorsal route is associated with conduction aphasia: comprehension and fluent speech are preserved, but repeating words is impaired.",
      },
      {
        key: "planning-speech",
        region: "frontal",
        title: "Planning speech",
        body: "[[frontal|Broca’s area]], in the left inferior frontal gyrus, is involved in planning speech. Recordings show it is most active just before speaking, while the sequence of sounds is prepared, and less active during speaking.",
        fact: "Its exact role is debated. Some research groups place speech planning here; others point to the middle precentral gyrus, just behind it, as the main region for sequencing syllables.",
      },
      {
        key: "articulation",
        region: "motor",
        title: "Controlling articulation",
        body: "[[motor|Speech motor cortex]], at the lower end of the precentral gyrus, controls the lips, jaw, tongue and larynx through the brainstem. While speaking, people hear their own voice and use this feedback to correct errors.",
        fact: "When the sound of their own voice is delayed by about 0.2 seconds, fluent speakers start to stumble.",
        signal: [[["frontal", "motor"]], [["motor", "a1"]]],
      },
    ],
    edges: [
      {
        from: "a1",
        to: "temporal",
        bend: [0, -0.08, -0.08],
      },
      {
        from: "temporal",
        to: "spt",
        bend: [0, 0.05, -0.1],
      },
      {
        from: "spt",
        to: "frontal",
        bend: [0, 0.28, -0.18],
      },
      {
        from: "frontal",
        to: "motor",
        bend: [0, 0.06, -0.12],
      },
      {
        from: "temporal",
        to: "meaning",
        bend: [0, -0.2, -0.15],
        kind: "branch",
      },
      {
        from: "motor",
        to: "a1",
        bend: [0, 0, -0.15],
        kind: "feedback",
      },
    ],
    sourceIds: ["language-streams", "parallel-speech", "broca-timing", "speech-planning-debate", "articulation", "language-network"],
  },
  {
    id: "loop",
    title: "Cortex–thalamus feedback",
    short: "Feedback",
    subtitle: "How the cortex adjusts its input and relays through the thalamus",
    color: "#bda0ff",
    icon: "loop",
    intro:
      "Sensory signals pass from the thalamus to the cortex, and the cortex sends two kinds of output back to the thalamus. Layer 6 feedback increases or reduces how much the thalamus passes on. Layer 5 output drives higher-order thalamic nuclei, such as the pulvinar, which relay it to other cortical areas. The example uses vision; hearing and touch have a similar circuit.",
    insight:
      "The cortex can adjust its own sensory input at the thalamus, through direct excitation from layer 6 and through inhibition via the TRN. This circuit is involved in attention and also produces sleep spindles, a brain rhythm seen in light sleep. Through layer 5, the thalamus also carries signals from one cortical area to another, in parallel with the direct connections between them.",
    caveat:
      "This example uses vision. The rate-dependent switch between reducing and increasing relay activity was shown in the mouse touch (somatosensory) thalamus, not measured in human vision. Synapse counts come from cats. Most evidence for the layer 5 route through the thalamus comes from mice, and the behavioural test used their whiskers; in cats and monkeys, the evidence is mainly anatomical. The atlas does not include a separate TRN or pulvinar, so their highlights show the whole thalamus. Layers 5 and 6 share V1’s location, within about 2 millimetres of the surface. Layer 5 of higher visual areas also projects to the pulvinar; only the route from V1 is drawn.",
    steps: [
      {
        key: "lgn-input",
        region: "lgn",
        title: "Input to the LGN",
        body: "[[lgn|LGN]] relay cells receive signals from the retina and pass them to the cortex. Retinal inputs are called “drivers” because they carry the visual information that is relayed.",
        fact: "In cats, about 7% of the synapses on an LGN relay cell come from the retina. About 30% come from the cortex, about 30% from the brainstem and about 30% from inhibitory cells.",
        signal: [],
      },
      {
        key: "cortex-input",
        region: "v1",
        title: "Input to the cortex",
        body: "LGN axons arrive mainly in layer 4 of [[v1|V1]], the main input layer of the cortex. Activity then spreads to the other five layers.",
        fact: "In general, layer 4 receives thalamic input, layers 2–3 connect to other cortical areas, and layers 5–6 send output to the thalamus and other structures.",
      },
      {
        key: "layer-6-feedback",
        region: "l6",
        title: "Feedback from layer 6",
        body: "Neurons in [[l6|layer 6]] send axons back to the LGN, where they excite the relay cells. This feedback is called a “modulator”: it does not carry visual information itself, but it changes how relay cells respond to it.",
        fact: "Layer 6 supplies about 30% of the synapses on LGN relay cells, roughly four times the retina’s share (cat data).",
        signal: [[["v1", "l6"]], [["l6", "lgn"]]],
      },
      {
        key: "trn-inhibition",
        region: "trn",
        title: "Inhibition through the TRN",
        body: "The same layer 6 axons have branches to the [[trn|thalamic reticular nucleus]] (TRN), a thin layer of inhibitory neurons around the thalamus. TRN neurons inhibit the relay cells. This allows the cortex to both increase and decrease activity in its own input.",
        fact: "In mouse brain slices, slow layer 6 activity mainly reduced relay-cell activity, while activity at around 10 pulses per second increased it. A 2024 study in awake mice found the same rate-dependent effect.",
        signal: [[["l6", "trn"]], [["trn", "lgn"]]],
      },
      {
        key: "layer-5-route",
        region: "l5",
        title: "A second route through the thalamus",
        body: "Neurons in [[l5|layer 5]], just above layer 6, send a second kind of output to the thalamus. Their axons end in higher-order nuclei such as the [[pulvinar|pulvinar]], whose main input comes from the cortex. In cats and monkeys, these axons have large terminals, a typical feature of driver inputs such as the retinal input to the LGN. The pulvinar relays the signal to [[extrastriate|higher visual areas]], in parallel with the direct connections from V1. Many of the same layer 5 axons also branch to brainstem centres that control movement, such as the superior colliculus.",
        fact: "In mice, blocking the layer 5 input from touch cortex to the higher-order touch thalamus severely impaired a whisker-based texture discrimination task, even though the direct connections between cortical areas were intact.",
        signal: [[["v1", "l5"]], [["l5", "pulvinar"]], [["pulvinar", "extrastriate"]]],
      },
    ],
    edges: [
      {
        from: "lgn",
        to: "v1",
        bend: [0, 0.1, 0.26],
      },
      {
        from: "v1",
        to: "l6",
        bend: [0.06, 0.1, 0.04],
      },
      {
        from: "l6",
        to: "trn",
        bend: [-0.1, 0.14, 0.05],
        kind: "feedback",
      },
      {
        from: "trn",
        to: "lgn",
        bend: [-0.12, -0.08, 0.025],
        kind: "inhibitory",
      },
      {
        from: "l6",
        to: "lgn",
        bend: [0, -0.25, 0.22],
        kind: "feedback",
      },
      {
        from: "v1",
        to: "l5",
        bend: [0, 0, 0],
      },
      {
        from: "l5",
        to: "pulvinar",
        bend: [0, 0, 0],
      },
      {
        from: "pulvinar",
        to: "extrastriate",
        bend: [0, 0, 0],
      },
    ],
    sourceIds: ["thalamus", "lgn-synapses", "switch", "ct-awake", "transthalamic", "transthalamic-review"],
  },
  {
    id: "attention",
    title: "Attention",
    short: "Attention",
    subtitle: "How the brain sets priorities",
    color: "#eed183",
    icon: "attention",
    intro:
      "The senses provide more information than the brain can process in detail. Attention increases the processing of some signals and reduces others. Several systems are involved: a frontal and parietal network that follows current goals, networks that respond to unexpected or important events, brainstem nuclei that set arousal, and the superior colliculus and thalamus below the cortex.",
    insight:
      "Attention changes how strongly sensory neurons respond (their gain). Directing the eyes and directing attention share much of their circuitry: the frontal eye fields, parietal cortex and superior colliculus each hold a map of space used for both, although researchers disagree about how completely the two overlap. Goal-driven and event-driven networks interact, neuromodulators such as noradrenaline and acetylcholine adjust the overall state, and the thalamus helps coordinate the areas involved. Unattended signals are weakened but still processed.",
    caveat:
      "A simplified example with three senses. The gold links show that these networks interact; they are not a fixed sequence or traced fibres. Most regions are drawn in the left hemisphere, although all of them exist on both sides; the temporoparietal junction is drawn on the right, where the ventral attention network is stronger. The frontal eye fields and temporoparietal junction are markers at typical positions from group studies and vary by around a centimetre between people. The superior colliculus, locus coeruleus and pulvinar are not in the atlas; their markers are approximate positions inside the midbrain, pons and thalamus. The basal forebrain, the main source of acetylcholine for the cortex, is not drawn. Dopamine, the basal ganglia, memory systems and the default mode network are not shown. The numbers in the Streams tab come from a simplified model, not measurements.",
    steps: [
      {
        key: "holding-a-goal",
        region: "pfc",
        title: "Holding a goal",
        body: "When you search for something, such as a friend in a crowd, [[pfc|prefrontal cortex]] keeps the goal active. Together with the [[fef|frontal eye fields]] and [[parietal|parietal cortex]], it sends signals to sensory areas that favour the features and locations that match the goal. This is called goal-driven, or top-down, attention.",
        fact: "In brain imaging, activity in visual areas increases while people wait for a stimulus at an attended location, before anything appears. Frontal and parietal areas show larger increases.",
        signal: [],
      },
      {
        key: "eye-fields",
        region: "fef",
        title: "Steering the eyes and attention",
        body: "The [[fef|frontal eye fields]] (FEF), in the precentral sulcus, move the eyes toward chosen locations. They also shift attention to a location without moving the eyes, which is called covert attention. Each FEF site corresponds to one part of the visual field. In monkeys, stimulating an FEF site with a current too weak to move the eyes improved performance on an attention task, but only when the attended object was in that site's part of the field. In humans, magnetic stimulation (TMS) of the right FEF changed activity in visual areas V1 to V4 and made stimuli in the periphery look higher in contrast than central ones.",
        fact: "In monkeys, the same weak FEF stimulation increased the responses of V4 neurons to stimuli at the matching location. Stimulating FEF sites for other locations could reduce them.",
      },
      {
        key: "priority-map",
        region: "parietal",
        title: "Priority map",
        body: "[[parietal|Parietal cortex]] around the intraparietal sulcus represents where things are and how much each one matters at the moment. In monkeys, activity in the lateral intraparietal area (LIP) has been described as a priority map: it combines a fast response to whatever appears with top-down signals such as a planned eye movement, and the location with the highest activity is used to guide attention and the next eye movement. With the [[fef|frontal eye fields]], this region forms the dorsal attention network, which directs attention voluntarily and is active in both hemispheres.",
        fact: "In monkeys, the pattern of activity across the whole LIP map tracked where the animal's attention was and how it shifted over time. Activity at a single location did not by itself predict where the monkey would attend or look.",
        signal: [
          [
            ["fef", "parietal"],
            ["a1", "parietal"],
            ["s1", "parietal"],
          ],
        ],
      },
      {
        key: "reorienting",
        region: "tpj",
        title: "Reorienting to the unexpected",
        body: "When something unexpected but relevant happens, such as a sound behind you or a movement at the edge of view, attention has to leave its current focus. This engages the ventral attention network: the [[tpj|temporoparietal junction]] (TPJ) and the inferior frontal cortex, mainly in the right hemisphere. The TPJ responds to changes in what you see, hear and feel. Its activity drops during focused attention, which may help keep distractions out. When a relevant event occurs, it is thought to interrupt the dorsal network so that attention can move to the event.",
        fact: "Spatial neglect, in which a person does not attend to the left side of space, usually follows damage to the right hemisphere, typically the inferior parietal lobule, superior temporal gyrus or inferior frontal gyrus. Which of these areas is most critical is debated.",
        signal: [
          [
            ["extrastriate", "tpj"],
            ["a1R", "tpj"],
          ],
          [["tpj", "fef"]],
        ],
      },
      {
        key: "salience",
        region: "insula",
        title: "Detecting important events",
        body: "The anterior [[insula|insula]] and [[cingulate|anterior cingulate cortex]] form the salience network. It responds to events that are important at the moment, such as a sudden change in a sound, sight or touch, or pain, and can shift attention away from the current task. It overlaps with the ventral attention network: the right anterior insula is active when attention is reoriented, and at rest the [[tpj|TPJ]]'s activity rises and falls with the insula and cingulate cortex. Some researchers treat the two as one network; others keep them separate. One hypothesis, still debated, is that the salience network switches the brain between internally focused and task-focused states.",
        fact: "The anterior insula also processes signals from inside the body. People who are better at detecting their own heartbeat show more activity in the right anterior insula.",
        signal: [],
      },
      {
        key: "adjusting-control",
        region: "cingulate",
        title: "Adjusting control",
        body: "The [[cingulate|anterior cingulate cortex]] is active when responses conflict or when an error is made. It works with prefrontal cortex to increase control on the next attempt. In monkeys, it also sends direct input to the [[lc|locus coeruleus]].",
        fact: "A standard example is the Stroop task: naming the ink colour of the word RED printed in blue. Anterior cingulate activity increases on these conflicting trials.",
        signal: [[["insula", "cingulate"]], [["cingulate", "pfc"]]],
      },
      {
        key: "arousal",
        region: "lc",
        title: "Arousal and neuromodulators",
        body: "How alert you are affects how well you can attend. The [[lc|locus coeruleus]], a small nucleus in the upper pons, is the main source of noradrenaline (norepinephrine) for the cortex. According to the adaptive gain theory, brief bursts of its activity help carry out the current task, while a steadier, tonic pattern goes with disengaging and looking for alternatives. Acetylcholine, a second chemical involved in attention, reaches the cortex mainly from the basal forebrain, which is not shown in the model. In monkey V1, adding small amounts of acetylcholine increased the effect of attention on neurons, and blocking its muscarinic receptors reduced it.",
        fact: "In monkeys doing a vigilance task, locus coeruleus neurons fired a brief burst about 90 ms after a rare target appeared, roughly 200 ms before the monkey responded. The bursts were weaker during periods of poor performance.",
        signal: [
          [["cingulate", "lc"]],
          [
            ["lc", "pfc"],
            ["lc", "extrastriate"],
          ],
        ],
      },
      {
        key: "midbrain-priority-map",
        region: "sc",
        title: "Priority map in the midbrain",
        body: "The [[sc|superior colliculus]] (SC), on the roof of the midbrain, contains a map of the space around you. It receives signals directly from the eyes and from the [[fef|frontal eye fields]] and [[parietal|parietal cortex]], and it turns the eyes and head toward targets. In monkeys, it is also needed for covert attention. When part of the SC was temporarily silenced, monkeys largely ignored motion in the matching part of the visual field if a distractor with conflicting information appeared elsewhere; with an uninformative distractor, their performance was largely unaffected. Weak stimulation of an SC site improved visual performance at the matching location without moving the eyes.",
        fact: "When the SC was silenced, monkeys had large attention deficits, yet attention still increased the responses of neurons in visual areas MT and MST. This suggests the SC supports attention through a route separate from the familiar effects in visual cortex.",
        signal: [
          [
            ["fef", "sc"],
            ["parietal", "sc"],
          ],
        ],
      },
      {
        key: "thalamic-coordination",
        region: "pulvinar",
        title: "Thalamic coordination",
        body: "The [[pulvinar|pulvinar]] is the largest nucleus of the primate thalamus and connects visual areas with each other. It also relays signals from the [[sc|superior colliculus]] to the cortex: in monkeys, some pulvinar neurons receive input from the SC and project to [[mt|area MT]]. In monkeys, pulvinar activity synchronized connected visual areas according to where the animal was attending.",
        fact: "The thalamus can also reduce input from a whole sense. In mice, prefrontal cortex, acting through the basal ganglia and the TRN, reduces the thalamic relay of the sense that should be ignored.",
        signal: [
          [
            ["sc", "pulvinar"],
            ["parietal", "pulvinar"],
          ],
        ],
      },
      {
        key: "sensory-effects",
        region: "extrastriate",
        title: "Effects in sensory cortex",
        body: "In sensory cortex, attention increases the responses of neurons that represent the attended item and makes them more consistent. Responses to other items are reduced. In monkeys, the increase is about 25% in visual area V4 and under 10% in V1. Unattended signals are still processed and can still draw attention.",
        fact: "The normalization model describes this with one equation: each response is divided by the combined activity of nearby neurons, so increasing one input reduces the others. The Streams tab shows a simplified version.",
        signal: [
          [
            ["pulvinar", "extrastriate"],
            ["fef", "extrastriate"],
            ["parietal", "a1"],
            ["parietal", "s1"],
          ],
        ],
      },
    ],
    edges: [
      {
        from: "pfc",
        to: "fef",
        bend: [0, 0, 0],
      },
      {
        from: "fef",
        to: "parietal",
        bend: [0, 0, 0],
      },
      {
        from: "fef",
        to: "extrastriate",
        channel: "vision",
        kind: "feedback",
        bend: [0, 0, 0],
      },
      {
        from: "parietal",
        to: "pulvinar",
        channel: "vision",
        bend: [0, 0, -0.06],
      },
      {
        from: "pulvinar",
        to: "extrastriate",
        channel: "vision",
        bend: [0, 0.15, 0.2],
      },
      {
        from: "extrastriate",
        to: "parietal",
        channel: "vision",
        bend: [0, -0.05, -0.05],
        kind: "feedback",
      },
      {
        from: "a1",
        to: "parietal",
        channel: "hearing",
        bend: [0, 0.12, -0.07],
        kind: "branch",
      },
      {
        from: "s1",
        to: "parietal",
        channel: "touch",
        bend: [0, 0.09, 0.04],
        kind: "branch",
      },
      {
        from: "insula",
        to: "cingulate",
        bend: [-0.08, 0.18, 0],
        kind: "branch",
      },
      {
        from: "cingulate",
        to: "pfc",
        bend: [0, 0.13, -0.12],
        kind: "feedback",
      },
      {
        from: "parietal",
        to: "a1",
        channel: "hearing",
        bend: [0, 0.16, 0.12],
        kind: "feedback",
      },
      {
        from: "parietal",
        to: "s1",
        channel: "touch",
        bend: [0, 0.12, -0.09],
        kind: "feedback",
      },
      {
        from: "extrastriate",
        to: "tpj",
        channel: "vision",
        bend: [0, 0, 0],
        detail: true,
      },
      {
        from: "a1R",
        to: "tpj",
        channel: "hearing",
        bend: [0, 0, 0],
        detail: true,
      },
      {
        from: "tpj",
        to: "fef",
        bend: [0, 0, 0],
        detail: true,
      },
      {
        from: "cingulate",
        to: "lc",
        bend: [0, 0, 0],
        detail: true,
      },
      {
        from: "lc",
        to: "pfc",
        kind: "branch",
        bend: [0, 0, 0],
        detail: true,
      },
      {
        from: "lc",
        to: "extrastriate",
        channel: "vision",
        kind: "branch",
        bend: [0, 0, 0],
        detail: true,
      },
      {
        from: "fef",
        to: "sc",
        bend: [0, 0, 0],
        detail: true,
      },
      {
        from: "parietal",
        to: "sc",
        bend: [0, 0, 0],
        detail: true,
      },
      {
        from: "sc",
        to: "pulvinar",
        channel: "vision",
        bend: [0, 0, 0],
        detail: true,
      },
    ],
    sourceIds: [
      "attention-networks",
      "salience",
      "normalization",
      "attention-gain",
      "baseline",
      "pulvinar",
      "trn-selection",
      "trn-basal-ganglia",
      "fef-v4",
      "fef-tms",
      "lip-priority",
      "reorienting",
      "network-taxonomy",
      "neglect-networks",
      "sc-attention",
      "sc-inactivation",
      "lc-adaptive-gain",
      "ach-v1",
      "neuromodulation",
    ],
  },
];
