import type { Pathway } from "./types";

export const pathways: Pathway[] = [
  {
    id: "vision",
    title: "Vision",
    short: "Vision",
    subtitle: "From the eye to visual cortex and beyond",
    color: "#77e8db",
    icon: "vision",
    intro:
      "The main visual pathway runs from the retina to the thalamus (LGN) and then to primary visual cortex (V1). From V1, two streams carry the signal onward: one into the temporal lobe, which identifies objects, and one into the parietal lobe, which locates them and guides movement.",
    insight:
      "The retina splits the image into parallel channels before it leaves the eye, and the LGN keeps them separate. At the chiasm, fibres are regrouped so that each hemisphere receives the opposite half of the visual field. V1 represents the visual field as local features such as edges. Beyond V1, the ventral stream identifies objects, with regions that prefer faces, places, bodies and words, and the dorsal stream processes motion and location to guide action.",
    caveat:
      "Both eyes connect to the chiasm; after that, the animation follows the route in the left hemisphere, which receives the right half of the visual field. Nerves, tracts and cortical routes are drawn as single curves; the real connections are many parallel fibre bundles that run in both directions, and the two streams exchange information at many points. Routes to the superior colliculus and pretectum are not shown. MT, IT and the category-selective areas are markers at typical positions from group studies; their positions vary by several millimetres between people, and the face area is usually larger in the right hemisphere. The V1 highlight follows the calcarine sulcus; the actual border varies between people.",
    steps: [
      {
        region: "retina",
        title: "Light becomes neural signals",
        body: "Rods (dim light) and cones (colour and detail) absorb light. In photoreceptors, light reduces electrical activity. Retinal circuits compare neighbouring points, so the output mainly reports contrast and change. Ganglion cells send this output through the optic nerve. Different types of ganglion cell carry different information: midget cells carry fine detail and red–green colour; parasol cells carry motion and changes in brightness.",
        fact: "About 96 million photoreceptors connect to roughly 1 million ganglion cells, so the signal is compressed around 100-fold before it leaves the eye.",
        signal: [],
      },
      {
        region: "chiasm",
        title: "Fibres cross at the optic chiasm",
        body: "The two optic nerves meet under the brain. Fibres from the half of each retina nearest the nose cross to the other side; fibres from the outer half do not. After this point, each hemisphere receives the opposite half of the visual field from both eyes.",
        fact: "About half of the fibres cross (commonly cited as 53%, from a single detailed count). This is why damage behind the chiasm affects the same half of the visual field in both eyes.",
      },
      {
        region: "lgn",
        title: "Parallel channels in the LGN",
        body: "Most optic tract fibres end in the [[lgn|lateral geniculate nucleus]] (LGN) of the thalamus. Its layers keep the two eyes separate and keep three channels apart. Magnocellular layers receive parasol cells: fast signals about motion and coarse shape. Parvocellular layers receive midget cells: slower signals about fine detail and red–green colour. Thin koniocellular layers carry blue–yellow colour. The LGN also receives more input from the cortex than from the eyes.",
        fact: "In monkeys, about 80% of retinal ganglion cells feed the parvocellular layers and about 10% the magnocellular layers. The fastest magnocellular responses arrive about 10 ms before the fastest parvocellular ones.",
      },
      {
        region: "v1",
        title: "Primary visual cortex (V1)",
        body: "The optic radiation carries LGN output to [[v1|primary visual cortex]] at the back of the brain. V1 contains a map of the visual field in which neighbouring points stay next to each other, and the centre of gaze takes up much more cortex than the periphery. Many V1 neurons respond best to edges at a specific orientation. V1 sends its output to many [[extrastriate|higher visual areas]].",
        fact: "The map is inverted: the upper visual field is represented below the calcarine sulcus and the lower field above it.",
      },
      {
        region: "extrastriate",
        title: "Two streams leave V1",
        body: "From V1, visual information travels along two main routes. The ventral stream runs down into the temporal lobe through areas V2 and V4 and identifies what things are. The dorsal stream runs up into the parietal lobe through [[mt|area MT]] and represents where things are and how to act on them. The dorsal stream receives mostly magnocellular input; the ventral stream receives both channels. The two streams exchange information at many points.",
        fact: "A patient known as D.F., with damage to her ventral stream, could not report how a slot was oriented, yet could post a card through it accurately. Her dorsal stream still guided the movement.",
        signal: [
          [
            ["v1", "extrastriate"],
            ["v1", "mt"],
          ],
        ],
      },
      {
        region: "mt",
        title: "Motion in area MT",
        body: "[[mt|Area MT]] (also called V5) is specialized for motion. Most of its neurons respond to movement in a particular direction and at a particular speed. In monkeys, electrically stimulating a small group of MT neurons shifts the animal's judgement of motion toward those neurons' preferred direction. A neighbouring area, MST, responds to the overall pattern of motion produced when you move through a scene (optic flow).",
        fact: "A patient with damage to this region on both sides lost most of her perception of motion. Pouring tea was difficult because the liquid appeared frozen.",
        signal: [[["v1", "mt"]]],
      },
      {
        region: "parietal",
        title: "Location and action in parietal cortex",
        body: "The dorsal stream continues from MT to [[parietal|posterior parietal cortex]]. Here, the position of things in view is combined with the position of the eyes, head and hand, so that vision can guide eye movements, reaching and grasping. The same region helps direct attention to locations (see the Attention topic).",
        fact: "Damage here can cause optic ataxia: a person can see and describe an object but reaches for it inaccurately.",
        signal: [[["mt", "parietal"]]],
      },
      {
        region: "it",
        title: "Object recognition in inferior temporal cortex",
        body: "The ventral stream runs from V1 through V2 and V4 to [[it|inferior temporal cortex]] (IT). Along the way, neurons respond to increasingly complex features: edges in V1, contours and simple shapes in V2 and V4, and objects and object parts in IT. IT responses stay similar when an object moves, changes size or is seen from a somewhat different angle.",
        fact: "In monkeys, the activity of about 100 IT neurons over as little as 12.5 ms was enough to tell which object was shown and its category, even when its position and size changed.",
        signal: [[["v1", "extrastriate"]], [["extrastriate", "it"]]],
      },
      {
        region: "ffa",
        title: "Areas for faces, places, bodies and words",
        body: "Some regions of temporal cortex respond more strongly to one category of image than to others. The [[ffa|fusiform face area]] prefers faces, the [[ppa|parahippocampal place area]] prefers places and scenes, the [[eba|extrastriate body area]] prefers bodies and body parts, and the [[vwfa|visual word form area]] prefers written words. Each responds most to its category but also responds to others, and the surrounding cortex carries category information too.",
        fact: "When a patient's fusiform face area was electrically stimulated, the faces of people in the room appeared distorted, while other objects looked normal.",
        signal: [
          [
            ["extrastriate", "ffa"],
            ["extrastriate", "ppa"],
            ["extrastriate", "eba"],
            ["extrastriate", "vwfa"],
          ],
        ],
      },
    ],
    edges: [
      { from: "retina", to: "chiasm", bend: [-0.1, -0.08, 0], stage: 0 },
      { from: "retinaR", to: "chiasm", bend: [-0.1, -0.08, 0], stage: 0 },
      { from: "chiasm", to: "lgn", bend: [0.06, -0.06, 0.03], stage: 1 },
      { from: "lgn", to: "v1", bend: [0.1, -0.18, 0.32], stage: 2 },
      { from: "v1", to: "extrastriate", bend: [0.12, 0, 0], detail: true },
      { from: "v1", to: "mt", bend: [0.15, 0.05, 0.05], detail: true },
      { from: "mt", to: "parietal", bend: [0.1, 0, 0.2], detail: true },
      { from: "extrastriate", to: "it", bend: [0, -0.15, 0.2], detail: true },
      { from: "extrastriate", to: "ffa", bend: [0, -0.18, 0], kind: "branch", detail: true },
      { from: "extrastriate", to: "ppa", bend: [0, -0.2, -0.05], kind: "branch", detail: true },
      { from: "extrastriate", to: "eba", bend: [0, 0, 0.15], kind: "branch", detail: true },
      { from: "extrastriate", to: "vwfa", bend: [0, -0.12, 0.08], kind: "branch", detail: true },
    ],
    sourceIds: [
      "visual",
      "visual-anatomy",
      "photoreceptors",
      "hubel-wiesel",
      "parallel-pathways",
      "two-streams",
      "mt-review",
      "object-recognition",
      "vtc-review",
    ],
  },
  {
    id: "touch",
    title: "Touch",
    short: "Touch",
    subtitle: "From skin and muscles to touch cortex",
    color: "#89bdf4",
    icon: "touch",
    intro:
      "Fine touch, vibration and the sense of body position travel on the dorsal column–medial lemniscus pathway. It crosses to the opposite side in the medulla, so each hemisphere receives input from the opposite side of the body.",
    insight:
      "The touch pathway follows the same general plan as the other senses: receptor, spinal cord, brainstem relay, thalamus, cortex. Because it crosses in the medulla, the left hemisphere processes touch from the right side of the body, and the reverse.",
    caveat:
      "The route shown runs from the right side of the body to the left hemisphere. Skin receptors, the spinal cord and the individual nuclei are not drawn; the medulla and thalamus highlights show the larger structures that contain them. Position sense from the legs partly uses a different spinal route. Pain and temperature use a separate pathway that crosses in the spinal cord, and the face uses the trigeminal nerve.",
    steps: [
      {
        region: "medulla",
        title: "Spinal cord and medulla",
        body: "Receptors in the skin, muscles and joints respond to pressure, vibration and stretch. Their nerve fibres enter the spinal cord and travel up the same side in the dorsal columns. In the medulla they connect to the [[medulla|dorsal column nuclei]], whose fibres then cross to the other side.",
        fact: "These fibres conduct at roughly 35–75 metres per second, which makes them some of the fastest sensory fibres in the body.",
        signal: [],
      },
      {
        region: "vpl",
        title: "Relay in the VPL",
        body: "The crossed fibres travel in the medial lemniscus to the [[vpl|ventral posterolateral nucleus]] (VPL) of the thalamus. The VPL is the thalamic relay for touch and body position from the body, as the LGN is for vision and the MGN for hearing.",
        fact: "Because of the crossing, the right hand is represented in the left thalamus and left cortex.",
      },
      {
        region: "s1",
        title: "Primary somatosensory cortex (S1)",
        body: "[[s1|Primary somatosensory cortex]] is on the postcentral gyrus and contains a map of the body. The hands, lips and tongue take up much more of this map than the back or legs. S1 has four narrow areas that emphasize different aspects (skin touch, texture, shape and limb position), although most neurons combine several types of input.",
        fact: "Wilder Penfield mapped this area by electrically stimulating the cortex of awake patients during epilepsy surgery; patients reported sensations in specific body parts.",
      },
      {
        region: "parietal",
        title: "Posterior parietal cortex",
        body: "[[parietal|Posterior parietal cortex]] combines touch with vision and body position to track where objects are relative to the body. This information is used for actions such as reaching and grasping.",
        fact: "Damage to this area, usually on the right, can cause neglect: the person does not attend to one side of space, sometimes including their own body.",
      },
    ],
    edges: [
      { from: "medulla", to: "vpl", bend: [0.07, 0.09, 0], stage: 0 },
      { from: "vpl", to: "s1", bend: [-0.03, 0.09, 0.15], stage: 1 },
      { from: "s1", to: "parietal", bend: [0.02, 0.08, 0.08], stage: 2 },
    ],
    sourceIds: ["body-sensation", "somatosensory-cortex"],
  },
  {
    id: "hearing",
    title: "Hearing",
    short: "Hearing",
    subtitle: "From the ear to auditory cortex",
    color: "#ed9bcc",
    icon: "hearing",
    intro:
      "Sound is converted into nerve signals in the cochlea and sorted by frequency. Several brainstem relays process the signal, including comparing the two ears to locate the sound, before it reaches the thalamus (MGN) and auditory cortex. Hearing has more relay stages before the cortex than vision or touch.",
    insight:
      "The auditory brainstem processes timing very precisely, which is needed to locate sounds. The frequency map set up in the cochlea (tonotopy) is kept at each stage up to the cortex.",
    caveat:
      "The main ascending routes are shown on both sides. The cochlea, auditory nerve, cochlear nuclei, inferior colliculi and geniculate bodies use atlas geometry; the superior olives are approximate positions inside the pons. Routes are drawn as curves, not traced fibres. The lateral lemniscus, routes that bypass the superior olive, and descending pathways to the ear are not shown.",
    steps: [
      {
        region: "cochlea",
        title: "Sound is sorted by frequency",
        body: "In the [[cochlea|cochlea]], the basilar membrane vibrates at different points for different frequencies: high frequencies near the base, low frequencies near the tip. Inner hair cells convert this movement into nerve signals. Outer hair cells change length to amplify quiet sounds and sharpen frequency tuning.",
        fact: "Each cochlea has about 3,500 inner hair cells, and 90–95% of auditory nerve fibres connect to them. In humans, hair cells that are lost do not regrow.",
        signal: [],
      },
      {
        region: "brainstem",
        title: "Cochlear nuclei",
        body: "Each auditory nerve ends in the [[brainstem|cochlear nuclei]] on the same side of the brainstem. Different cell types here extract different features, such as precise timing, loudness and frequency content, and send them along separate pathways.",
        fact: "This is the last stage where each ear is processed separately. After this, both hemispheres receive input from both ears.",
      },
      {
        region: "soc",
        title: "Comparing the two ears",
        body: "The [[soc|superior olivary complex]] is the first place where input from both ears is combined. The medial superior olive compares arrival times; the lateral superior olive compares loudness, which differs between the ears because the head blocks some of the sound. These differences are used to locate a sound horizontally.",
        fact: "People can detect arrival-time differences between the ears as small as about 10 microseconds (0.01 milliseconds).",
      },
      {
        region: "ic",
        title: "Inferior colliculus",
        body: "Nearly all ascending auditory pathways synapse in the [[ic|inferior colliculus]] in the midbrain. It combines timing, loudness and frequency information and sends signals to the superior colliculus, which helps turn the eyes and head toward a sound.",
        fact: "Because almost all ascending auditory signals pass through it, the inferior colliculus is described as a near-obligatory relay.",
      },
      {
        region: "mgn",
        title: "Relay in the MGN",
        body: "The [[mgn|medial geniculate nucleus]] (MGN) is the auditory relay of the thalamus. Its ventral part keeps the frequency map and projects to primary auditory cortex. Its other parts project to surrounding auditory areas and to the amygdala.",
        fact: "Like the LGN, the MGN receives large feedback projections from the cortex it sends to.",
      },
      {
        region: "a1",
        title: "Primary auditory cortex (A1)",
        body: "[[a1|Primary auditory cortex]] is on Heschl’s gyrus, inside the lateral sulcus. It is organized by frequency (tonotopy). Surrounding areas process more complex sounds, including speech, music and voices.",
        fact: "Because pathways cross at several levels, each hemisphere receives input from both ears. Damage to auditory cortex on one side rarely causes deafness in one ear.",
      },
    ],
    edges: [
      { from: "cochlea", to: "brainstem", bend: [-0.015, 0.012, 0], stage: 0 },
      { from: "cochleaR", to: "brainstemR", bend: [-0.015, 0.012, 0], stage: 0 },
      { from: "brainstem", to: "soc", bend: [-0.04, -0.03, 0], stage: 1 },
      { from: "brainstem", to: "socR", bend: [-0.045, -0.05, 0], stage: 1, kind: "branch" },
      { from: "brainstemR", to: "socR", bend: [-0.04, -0.03, 0], stage: 1 },
      { from: "brainstemR", to: "soc", bend: [-0.045, -0.05, 0], stage: 1, kind: "branch" },
      { from: "soc", to: "ic", bend: [0.09, 0, 0.05], stage: 2 },
      { from: "socR", to: "icR", bend: [0.09, 0, -0.05], stage: 2 },
      { from: "ic", to: "mgn", bend: [0.02, 0.025, 0.025], stage: 3 },
      { from: "icR", to: "mgnR", bend: [0.02, 0.025, -0.025], stage: 3 },
      { from: "mgn", to: "a1", bend: [-0.015, 0.07, 0.015], stage: 4 },
      { from: "mgnR", to: "a1R", bend: [-0.015, 0.07, -0.015], stage: 4 },
    ],
    sourceIds: ["ear-anatomy", "hair-cells", "auditory"],
  },
  {
    id: "speech",
    title: "Speech and language",
    short: "Speech",
    subtitle: "Hearing and producing speech",
    color: "#f8a47f",
    icon: "speech",
    intro:
      "Speech processing uses two connected streams. The ventral stream, in both hemispheres, maps speech sounds to meaning. The dorsal stream, mainly in the left hemisphere, maps speech sounds to the movements needed to produce them. Repeating a new word uses both.",
    insight:
      "Language depends on a network of regions, mostly in the left hemisphere, while word meaning is represented across both hemispheres. Speech also uses memory, attention and motor systems.",
    caveat:
      "A simplified version of the dual-stream model. Only left-hemisphere regions are drawn, although early speech processing happens in both hemispheres. Area Spt and Broca’s area are placed where they are usually found; their borders vary. The order of steps follows repeating a word; in normal speech these regions are active at the same time and exchange signals in both directions.",
    steps: [
      {
        region: "a1",
        title: "Hearing speech",
        body: "Speech first reaches [[a1|auditory cortex]] like any other sound. Recordings from the brain surface show that the nearby [[temporal|superior temporal gyrus]] receives speech input at the same time as primary auditory cortex, not after it.",
        fact: "In one study, stimulating primary auditory cortex caused sound hallucinations but did not affect word perception, while stimulating the superior temporal gyrus disrupted it. Surgical removal of primary auditory cortex did not impair speech perception.",
        signal: [],
      },
      {
        region: "temporal",
        title: "Recognizing speech sounds",
        body: "Neurons in the [[temporal|superior temporal gyrus]] respond to features of speech sounds, such as whether a consonant is made with the lips or the tongue. From here, the ventral stream links sounds to [[meaning|meaning]] in both hemispheres.",
        fact: "When two people speak at once, activity here mainly follows the speaker being attended to, clearly enough to identify which one.",
        signal: [[["a1", "temporal"]], [["temporal", "meaning"]]],
      },
      {
        region: "spt",
        title: "Linking sound and movement",
        body: "[[spt|Area Spt]], at the back end of the Sylvian fissure, links the sound of a word to the movements needed to say it. It responds both when hearing speech and when silently rehearsing it.",
        fact: "Damage along this dorsal route is associated with conduction aphasia: comprehension and fluent speech are preserved, but repeating words is impaired.",
      },
      {
        region: "frontal",
        title: "Planning speech",
        body: "[[frontal|Broca’s area]], in the left inferior frontal gyrus, is involved in planning speech. Recordings show it is most active just before speaking, while the sequence of sounds is prepared, and less active during speaking.",
        fact: "Its exact role is debated. Some research groups place speech planning here; others point to the middle precentral gyrus, just behind it, as the main region for sequencing syllables.",
      },
      {
        region: "motor",
        title: "Controlling articulation",
        body: "[[motor|Speech motor cortex]], at the lower end of the precentral gyrus, controls the lips, jaw, tongue and larynx through the brainstem. While speaking, people hear their own voice and use this feedback to correct errors.",
        fact: "When the sound of their own voice is delayed by about 0.2 seconds, fluent speakers start to stumble.",
        signal: [[["frontal", "motor"]], [["motor", "a1"]]],
      },
    ],
    edges: [
      { from: "a1", to: "temporal", bend: [0, -0.08, -0.08] },
      { from: "temporal", to: "spt", bend: [0, 0.05, -0.1] },
      { from: "spt", to: "frontal", bend: [0, 0.28, -0.18] },
      { from: "frontal", to: "motor", bend: [0, 0.06, -0.12] },
      { from: "temporal", to: "meaning", bend: [0, -0.2, -0.15], kind: "branch" },
      { from: "motor", to: "a1", bend: [0, 0, -0.15], kind: "feedback" },
    ],
    sourceIds: ["language-streams", "parallel-speech", "broca-timing", "speech-planning-debate", "articulation", "language-network"],
  },
  {
    id: "loop",
    title: "Cortex–thalamus feedback",
    short: "Feedback",
    subtitle: "How the cortex adjusts its own input",
    color: "#bda0ff",
    icon: "loop",
    intro:
      "Sensory signals pass from the thalamus to the cortex, and the cortex also sends a large projection back to the thalamus. This feedback can increase or reduce how much the thalamus passes on. The example uses vision; hearing and touch have the same circuit.",
    insight:
      "The cortex can adjust its own sensory input at the thalamus, through direct excitation and through inhibition via the TRN. This circuit is involved in attention and also produces sleep spindles, a brain rhythm seen in light sleep.",
    caveat:
      "This example uses vision. The rate-dependent switch between reducing and increasing relay activity was shown in the mouse touch (somatosensory) thalamus, not measured in human vision. Synapse counts come from cats. The atlas does not include a separate TRN, so its highlight shows the whole thalamus. Layer 6 is in the same location as V1, a few millimetres below the surface.",
    steps: [
      {
        region: "lgn",
        title: "Input to the LGN",
        body: "[[lgn|LGN]] relay cells receive signals from the retina and pass them to the cortex. Retinal inputs are called “drivers” because they carry the visual information that is relayed.",
        fact: "In cats, about 7% of the synapses on an LGN relay cell come from the retina. About 30% come from the cortex, about 30% from the brainstem and about 30% from inhibitory cells.",
        signal: [],
      },
      {
        region: "v1",
        title: "Input to the cortex",
        body: "LGN axons arrive mainly in layer 4 of [[v1|V1]], the main input layer of the cortex. Activity then spreads to the other five layers.",
        fact: "In general, layer 4 receives thalamic input, layers 2–3 connect to other cortical areas, and layers 5–6 send output to the thalamus and other structures.",
      },
      {
        region: "l6",
        title: "Feedback from layer 6",
        body: "Neurons in [[l6|layer 6]] send axons back to the LGN, where they excite the relay cells. This feedback is called a “modulator”: it does not carry visual information itself, but it changes how relay cells respond to it.",
        fact: "Layer 6 supplies about 30% of the synapses on LGN relay cells, roughly four times the retina’s share (cat data).",
        signal: [[["v1", "l6"]], [["l6", "lgn"]]],
      },
      {
        region: "trn",
        title: "Inhibition through the TRN",
        body: "The same layer 6 axons have branches to the [[trn|thalamic reticular nucleus]] (TRN), a thin layer of inhibitory neurons around the thalamus. TRN neurons inhibit the relay cells. This allows the cortex to both increase and decrease activity in its own input.",
        fact: "In mouse brain slices, slow layer 6 activity mainly reduced relay-cell activity, while activity at around 10 pulses per second increased it. A 2024 study in awake mice found the same rate-dependent effect.",
        signal: [[["l6", "trn"]], [["trn", "lgn"]]],
      },
    ],
    edges: [
      { from: "lgn", to: "v1", bend: [0, 0.1, 0.26] },
      { from: "v1", to: "l6", bend: [0.06, 0.1, 0.04] },
      { from: "l6", to: "trn", bend: [-0.1, 0.14, 0.05], kind: "feedback" },
      { from: "trn", to: "lgn", bend: [-0.12, -0.08, 0.025], kind: "inhibitory" },
      { from: "l6", to: "lgn", bend: [0, -0.25, 0.22], kind: "feedback" },
    ],
    sourceIds: ["thalamus", "lgn-synapses", "switch", "ct-awake"],
  },
  {
    id: "attention",
    title: "Attention",
    short: "Attention",
    subtitle: "How the brain sets priorities",
    color: "#eed183",
    icon: "attention",
    intro:
      "The senses provide more information than the brain can process in detail. Attention increases the processing of some signals and reduces others. Several systems are involved: frontal and parietal networks that follow current goals, a salience network that detects important events, and the thalamus.",
    insight:
      "Attention changes how strongly sensory neurons respond (their gain). Goal-related networks, salience-related networks and the thalamus all contribute. Unattended signals are reduced, not removed.",
    caveat:
      "A simplified example with three senses. The gold links show that these networks interact; they are not a fixed sequence or traced fibres. The ventral attention network (temporoparietal junction), the superior colliculus, memory and neuromodulators such as noradrenaline are not shown. The numbers in the Streams tab come from a simplified model, not measurements.",
    steps: [
      {
        region: "pfc",
        title: "Holding a goal",
        body: "When you search for something, such as a friend in a crowd, [[pfc|prefrontal cortex]] keeps the goal active. Together with the frontal eye fields, it sends signals to sensory areas that favour the features and locations that match the goal.",
        fact: "In brain imaging, activity in visual areas increases while people wait for a stimulus at an attended location, before anything appears. Frontal and parietal areas show larger increases.",
        signal: [],
      },
      {
        region: "parietal",
        title: "Priority map",
        body: "[[parietal|Parietal cortex]] around the intraparietal sulcus represents where things are and how relevant they are. With the frontal eye fields, it forms the dorsal attention network, which directs attention voluntarily.",
        fact: "Damage to the right parietal lobe can cause neglect of the left side of space.",
        signal: [
          [
            ["pfc", "parietal"],
            ["a1", "parietal"],
            ["s1", "parietal"],
          ],
        ],
      },
      {
        region: "insula",
        title: "Detecting important events",
        body: "The anterior [[insula|insula]] and [[cingulate|anterior cingulate cortex]] form the salience network. It responds to events that are important at the moment, such as a loud noise, your name or pain, and can shift attention away from the current task. One hypothesis, still debated, is that it switches the brain between internally focused and task-focused states.",
        fact: "The anterior insula also processes signals from inside the body. People who are better at detecting their own heartbeat show more activity in the right anterior insula.",
        signal: [],
      },
      {
        region: "cingulate",
        title: "Adjusting control",
        body: "The [[cingulate|anterior cingulate cortex]] is active when responses conflict or when an error is made. It works with prefrontal cortex to increase control on the next attempt.",
        fact: "A standard example is the Stroop task: naming the ink colour of the word RED printed in blue. Anterior cingulate activity increases on these conflicting trials.",
        signal: [[["insula", "cingulate"]], [["cingulate", "pfc"]]],
      },
      {
        region: "pulvinar",
        title: "Thalamic coordination",
        body: "The [[pulvinar|pulvinar]] is the largest nucleus of the primate thalamus and connects visual areas with each other. In monkeys, pulvinar activity synchronized connected visual areas according to where the animal was attending.",
        fact: "The thalamus can also reduce input from a whole sense. In mice, prefrontal cortex, acting through the basal ganglia and the TRN, reduces the thalamic relay of the sense that should be ignored.",
        signal: [[["parietal", "pulvinar"]]],
      },
      {
        region: "extrastriate",
        title: "Effects in sensory cortex",
        body: "In sensory cortex, attention increases the responses of neurons that represent the attended item and makes them more consistent. Responses to other items are reduced. In monkeys, the increase is about 25% in visual area V4 and under 10% in V1. Unattended signals are still processed and can still draw attention.",
        fact: "The normalization model describes this with one equation: each response is divided by the combined activity of nearby neurons, so increasing one input reduces the others. The Streams tab shows a simplified version.",
        signal: [
          [
            ["pulvinar", "extrastriate"],
            ["parietal", "a1"],
            ["parietal", "s1"],
          ],
        ],
      },
    ],
    edges: [
      { from: "pfc", to: "parietal", bend: [0, -0.22, -0.12] },
      { from: "parietal", to: "pulvinar", channel: "vision", bend: [0, 0, -0.06] },
      { from: "pulvinar", to: "extrastriate", channel: "vision", bend: [0, 0.15, 0.2] },
      { from: "extrastriate", to: "parietal", channel: "vision", bend: [0, -0.05, -0.05], kind: "feedback" },
      { from: "a1", to: "parietal", channel: "hearing", bend: [0, 0.12, -0.07], kind: "branch" },
      { from: "s1", to: "parietal", channel: "touch", bend: [0, 0.09, 0.04], kind: "branch" },
      { from: "insula", to: "cingulate", bend: [-0.08, 0.18, 0], kind: "branch" },
      { from: "cingulate", to: "pfc", bend: [0, 0.13, -0.12], kind: "feedback" },
      { from: "parietal", to: "a1", channel: "hearing", bend: [0, 0.16, 0.12], kind: "feedback" },
      { from: "parietal", to: "s1", channel: "touch", bend: [0, 0.12, -0.09], kind: "feedback" },
    ],
    sourceIds: ["attention-networks", "salience", "normalization", "attention-gain", "baseline", "pulvinar", "trn-selection", "trn-basal-ganglia"],
  },
];
