import type { Vec3 } from "math";
import atlas from "../data/atlas-data.json";
import areas from "../data/functional-areas.json";
import type { Region, RegionId } from "./types";

// Anchors come from the atlas; landmark centres stand in for nuclei it does not segment.
const at = (id: keyof typeof atlas.anchors): Vec3 => atlas.anchors[id] as Vec3;
const center = (name: keyof typeof atlas.landmarks): Vec3 => atlas.landmarks[name].center as Vec3;
// Functional areas the atlas does not segment; see scripts/place-functional-areas.mjs.
const area = (id: keyof typeof areas): Vec3 => areas[id].position as Vec3;

export const regions: Record<RegionId, Region> = {
  retina: {
    id: "retina",
    label: "Retina (left eye)",
    short: "Left retina",
    name: "the retina",
    where: "Lining the back of the left eye",
    position: at("retina"),
  },
  retinaR: {
    id: "retinaR",
    label: "Retina (right eye)",
    short: "Right retina",
    name: "the right retina",
    where: "Lining the back of the right eye",
    position: at("retinaR"),
  },
  chiasm: {
    id: "chiasm",
    label: "Optic chiasm",
    short: "Optic chiasm",
    name: "the optic chiasm",
    where: "Under the brain, just above the pituitary gland",
    position: at("chiasm"),
  },
  lgn: {
    id: "lgn",
    label: "Lateral geniculate nucleus (LGN)",
    short: "LGN · visual relay",
    name: "the LGN",
    where: "Thalamus, left side",
    position: at("lgn"),
  },
  v1: {
    id: "v1",
    label: "Primary visual cortex (V1)",
    short: "V1 · visual cortex",
    name: "primary visual cortex",
    where: "Occipital lobe, along the calcarine sulcus",
    position: at("v1"),
  },
  l6: {
    id: "l6",
    label: "Layer 6 of the cortex",
    short: "Layer 6 · feedback",
    name: "layer 6",
    where: "Deepest cell layer of V1 (same location, within about 2 millimetres of the surface)",
    position: at("l6"),
  },
  l5: {
    id: "l5",
    label: "Layer 5 of the cortex",
    short: "Layer 5 · to pulvinar",
    name: "layer 5",
    where: "Deep cell layer of V1, just above layer 6 (same location)",
    position: at("l5"),
  },
  trn: {
    id: "trn",
    label: "Thalamic reticular nucleus (TRN)",
    short: "TRN · inhibition",
    name: "the TRN",
    where: "A thin sheet covering the front and outer side of the thalamus",
    position: at("trn"),
  },
  pfc: {
    id: "pfc",
    label: "Prefrontal cortex",
    short: "Prefrontal cortex",
    name: "prefrontal cortex",
    where: "Front of the frontal lobe; the marker is on the middle frontal gyrus",
    position: at("pfc"),
  },
  parietal: {
    id: "parietal",
    label: "Posterior parietal cortex",
    short: "Parietal cortex",
    name: "parietal cortex",
    where: "Parietal lobe, superior parietal lobule and intraparietal sulcus",
    position: at("parietal"),
  },
  pulvinar: { id: "pulvinar", label: "Pulvinar", short: "Pulvinar", name: "the pulvinar", where: "Back of the thalamus", position: at("pulvinar") },
  extrastriate: {
    id: "extrastriate",
    label: "Higher visual areas",
    short: "Higher visual areas",
    name: "higher visual areas",
    where: "Occipital lobe, lateral surface",
    position: at("extrastriate"),
  },
  mt: {
    id: "mt",
    label: "Area MT (V5)",
    short: "MT · motion",
    name: "area MT",
    where: "Side of the brain, where the occipital and temporal lobes meet",
    position: area("mt"),
  },
  it: {
    id: "it",
    label: "Inferior temporal cortex (IT)",
    short: "IT · objects",
    name: "inferior temporal cortex",
    where: "Lower part of the side of the temporal lobe, around the inferior temporal sulcus",
    position: area("it"),
  },
  ffa: {
    id: "ffa",
    label: "Fusiform face area (FFA)",
    short: "FFA · faces",
    name: "the fusiform face area",
    where: "Fusiform gyrus, on the underside of the left temporal lobe",
    position: area("ffa"),
  },
  ppa: {
    id: "ppa",
    label: "Parahippocampal place area (PPA)",
    short: "PPA · places",
    name: "the parahippocampal place area",
    where: "Collateral sulcus, on the underside of the temporal lobe, toward the midline",
    position: area("ppa"),
  },
  eba: {
    id: "eba",
    label: "Extrastriate body area (EBA)",
    short: "EBA · bodies",
    name: "the extrastriate body area",
    where: "Side of the brain, where the occipital and temporal lobes meet, next to MT",
    position: area("eba"),
  },
  vwfa: {
    id: "vwfa",
    label: "Visual word form area (VWFA)",
    short: "VWFA · words",
    name: "the visual word form area",
    where: "Left occipitotemporal sulcus, on the underside of the temporal lobe",
    position: area("vwfa"),
  },
  cochlea: {
    id: "cochlea",
    label: "Cochlea (left)",
    short: "Left cochlea",
    name: "the cochlea",
    where: "Inner ear, inside the left temporal bone",
    position: at("cochlea"),
  },
  cochleaR: {
    id: "cochleaR",
    label: "Cochlea (right)",
    short: "Right cochlea",
    name: "the right cochlea",
    where: "Inner ear, inside the right temporal bone",
    position: at("cochleaR"),
  },
  brainstem: {
    id: "brainstem",
    label: "Cochlear nuclei (left)",
    short: "Cochlear nuclei",
    name: "the cochlear nuclei",
    where: "Brainstem, where the pons meets the medulla, left side",
    position: at("brainstem"),
  },
  brainstemR: {
    id: "brainstemR",
    label: "Cochlear nuclei (right)",
    short: "Right cochlear nuclei",
    name: "the right cochlear nuclei",
    where: "Brainstem, right side",
    position: at("brainstemR"),
  },
  soc: {
    id: "soc",
    label: "Superior olivary complex (left)",
    short: "Superior olive",
    name: "the superior olive",
    where: "Lower pons, left side",
    position: at("soc"),
  },
  socR: {
    id: "socR",
    label: "Superior olivary complex (right)",
    short: "Right superior olive",
    name: "the right superior olive",
    where: "Lower pons, right side",
    position: at("socR"),
  },
  ic: {
    id: "ic",
    label: "Inferior colliculus (left)",
    short: "Inferior colliculus",
    name: "the inferior colliculus",
    where: "Roof of the midbrain, left side",
    position: at("ic"),
  },
  icR: {
    id: "icR",
    label: "Inferior colliculus (right)",
    short: "Right colliculus",
    name: "the right inferior colliculus",
    where: "Roof of the midbrain, right side",
    position: at("icR"),
  },
  mgn: {
    id: "mgn",
    label: "Medial geniculate nucleus (MGN, left)",
    short: "MGN · sound relay",
    name: "the MGN",
    where: "Thalamus, left side",
    position: at("mgn"),
  },
  mgnR: {
    id: "mgnR",
    label: "Medial geniculate nucleus (right)",
    short: "Right MGN",
    name: "the right MGN",
    where: "Thalamus, right side",
    position: at("mgnR"),
  },
  a1: {
    id: "a1",
    label: "Primary auditory cortex (A1)",
    short: "A1 · auditory cortex",
    name: "auditory cortex",
    where: "Heschl’s gyrus, folded inside the left lateral sulcus",
    position: at("a1"),
  },
  a1R: {
    id: "a1R",
    label: "Primary auditory cortex (right)",
    short: "Right A1",
    name: "right auditory cortex",
    where: "Heschl’s gyrus, right hemisphere",
    position: at("a1R"),
  },
  temporal: {
    id: "temporal",
    label: "Superior temporal gyrus",
    short: "Speech-sound cortex",
    name: "the superior temporal gyrus",
    where: "Upper gyrus of the left temporal lobe, on the side of the brain",
    position: at("temporal"),
  },
  spt: {
    id: "spt",
    label: "Area Spt",
    short: "Area Spt",
    name: "area Spt",
    where: "Back of the planum temporale, inside the Sylvian fissure, left side",
    position: at("spt"),
  },
  frontal: {
    id: "frontal",
    label: "Broca’s area (inferior frontal gyrus)",
    short: "Broca’s area",
    name: "Broca’s area",
    where: "Left inferior frontal gyrus",
    position: at("frontal"),
  },
  motor: {
    id: "motor",
    label: "Speech motor cortex",
    short: "Speech motor cortex",
    name: "speech motor cortex",
    where: "Lower end of the left precentral gyrus",
    position: at("motor"),
  },
  meaning: {
    id: "meaning",
    label: "Meaning (semantic) networks",
    short: "Meaning networks",
    name: "meaning networks",
    where: "Temporal lobe and beyond, both hemispheres",
    position: at("meaning"),
  },
  medulla: {
    id: "medulla",
    label: "Dorsal column nuclei",
    short: "Medulla · first relay",
    name: "the dorsal column nuclei",
    where: "Lower medulla, right side",
    position: center("Medulla_oblongatar"),
  },
  vpl: {
    id: "vpl",
    label: "Ventral posterolateral nucleus (VPL)",
    short: "VPL · touch relay",
    name: "the VPL",
    where: "Thalamus, left side",
    position: center("Thalamusl"),
  },
  s1: {
    id: "s1",
    label: "Primary somatosensory cortex (S1)",
    short: "S1 · touch cortex",
    name: "touch cortex (S1)",
    where: "Postcentral gyrus, left hemisphere",
    position: center("Postcentral_gyrusl"),
  },
  insula: {
    id: "insula",
    label: "Insula",
    short: "Insula",
    name: "the insula",
    where: "Folded deep inside the lateral sulcus",
    position: center("Circular_sulcus_of_insulal"),
  },
  cingulate: {
    id: "cingulate",
    label: "Anterior cingulate cortex (dorsal)",
    short: "Cingulate cortex",
    name: "the cingulate cortex",
    where: "Inner (medial) surface of the hemisphere, on the cingulate gyrus above the corpus callosum",
    position: center("Cingulate_gyrus_and_sulcus_(Middle_anterior_part)l"),
  },
  fef: {
    id: "fef",
    label: "Frontal eye fields (FEF)",
    short: "FEF · gaze control",
    name: "the frontal eye fields",
    where: "Frontal lobe, precentral sulcus near the superior frontal sulcus",
    position: area("fef"),
  },
  sc: {
    id: "sc",
    label: "Superior colliculus (SC)",
    short: "SC · orienting",
    name: "the superior colliculus",
    where: "Roof of the midbrain, just above the inferior colliculus, left side",
    position: at("sc"),
  },
  tpj: {
    id: "tpj",
    label: "Temporoparietal junction (TPJ, right)",
    short: "TPJ · reorienting",
    name: "the temporoparietal junction",
    where: "Right hemisphere, where the temporal and parietal lobes meet",
    position: area("tpj"),
  },
  lc: {
    id: "lc",
    label: "Locus coeruleus (LC)",
    short: "LC · noradrenaline",
    name: "the locus coeruleus",
    where: "Upper pons, beside the floor of the fourth ventricle, left side",
    position: at("lc"),
  },
  dorsalHorn: {
    id: "dorsalHorn",
    label: "Dorsal horn of the spinal cord",
    short: "Dorsal horn · pain",
    name: "the dorsal horn",
    where: "Spinal cord, right side (below the model; marked at the lower end of the medulla)",
    position: at("dorsalHorn"),
  },
  s2: {
    id: "s2",
    label: "Secondary somatosensory cortex (S2)",
    short: "S2 · touch & pain",
    name: "secondary somatosensory cortex (S2)",
    where: "Parietal operculum, upper bank of the left lateral sulcus",
    position: area("s2"),
  },
  postInsula: {
    id: "postInsula",
    label: "Posterior insula",
    short: "Posterior insula",
    name: "the posterior insula",
    where: "Back part of the insula, deep inside the left lateral sulcus",
    position: area("postInsula"),
  },
  belt: {
    id: "belt",
    label: "Auditory belt and parabelt",
    short: "Belt · complex sounds",
    name: "the belt and parabelt",
    where: "Around Heschl’s gyrus and along the upper superior temporal gyrus, left side",
    position: area("belt"),
  },
  astg: {
    id: "astg",
    label: "Anterior superior temporal gyrus",
    short: "aSTG · sound identity",
    name: "the anterior superior temporal gyrus",
    where: "Front part of the superior temporal gyrus, left side",
    position: area("astg"),
  },
  vlpfc: {
    id: "vlpfc",
    label: "Ventrolateral prefrontal cortex",
    short: "vlPFC · what stream",
    name: "ventrolateral prefrontal cortex",
    where: "Left inferior frontal gyrus, triangular part",
    position: area("vlpfc"),
  },
};
