import type { Source } from "./types";

export const sources: Source[] = [
  {
    id: "visual",
    title: "Central projections of retinal ganglion cells",
    author: "Purves et al. · Neuroscience, 2nd ed. · 2001",
    url: "https://www.ncbi.nlm.nih.gov/books/NBK11145/",
    note: "Retina → LGN → V1, partial crossing at the chiasm, and non-geniculate targets.",
  },
  {
    id: "visual-anatomy",
    title: "Neuroanatomy, visual pathway",
    author: "StatPearls · NCBI Bookshelf",
    url: "https://www.ncbi.nlm.nih.gov/books/NBK553189/",
    note: "Optic chiasm, visual-field organization, optic radiations and V1.",
  },
  {
    id: "photoreceptors",
    title: "Human photoreceptor topography",
    author: "Curcio et al. · Journal of Comparative Neurology · 1990",
    url: "https://doi.org/10.1002/cne.902920402",
    note: "Counts of rods and cones in human retinas.",
  },
  {
    id: "hubel-wiesel",
    title: "Receptive fields of single neurones in the cat’s striate cortex",
    author: "Hubel & Wiesel · Journal of Physiology · 1959",
    url: "https://doi.org/10.1113/jphysiol.1959.sp006308",
    note: "The discovery of orientation-selective neurons in primary visual cortex.",
  },
  {
    id: "parallel-pathways",
    title: "Parallel processing strategies of the primate visual system",
    author: "Nassi & Callaway · Nature Reviews Neuroscience · 2009",
    url: "https://doi.org/10.1038/nrn2619",
    note: "Magnocellular, parvocellular and koniocellular channels, and how they feed the cortical streams.",
  },
  {
    id: "two-streams",
    title: "Separate visual pathways for perception and action",
    author: "Goodale & Milner · Trends in Neurosciences · 1992",
    url: "https://doi.org/10.1016/0166-2236(92)90344-8",
    note: "The ventral stream for recognition and the dorsal stream for guiding action, including patient D.F.",
  },
  {
    id: "mt-review",
    title: "Structure and function of visual area MT",
    author: "Born & Bradley · Annual Review of Neuroscience · 2005",
    url: "https://doi.org/10.1146/annurev.neuro.26.041002.131052",
    note: "Direction and speed tuning in MT and its role in motion perception.",
  },
  {
    id: "object-recognition",
    title: "How does the brain solve visual object recognition?",
    author: "DiCarlo, Zoccolan & Rust · Neuron · 2012",
    url: "https://doi.org/10.1016/j.neuron.2012.01.010",
    note: "How the ventral stream builds object representations that tolerate changes in position, size and view.",
  },
  {
    id: "vtc-review",
    title: "The functional architecture of the ventral temporal cortex and its role in categorization",
    author: "Grill-Spector & Weiner · Nature Reviews Neuroscience · 2014",
    url: "https://doi.org/10.1038/nrn3747",
    note: "Where the face, place, body and word areas lie and how they relate to the anatomy.",
  },
  {
    id: "ear-anatomy",
    title: "Neuroanatomy, auditory pathway",
    author: "StatPearls · NCBI Bookshelf",
    url: "https://www.ncbi.nlm.nih.gov/books/NBK532311/",
    note: "Cochlea, ipsilateral cochlear nuclei, bilateral brainstem routes, midbrain and thalamic relays.",
  },
  {
    id: "auditory",
    title: "Integrating information from the two ears",
    author: "Purves et al. · Neuroscience, 2nd ed. · 2001",
    url: "https://www.ncbi.nlm.nih.gov/books/NBK10820/",
    note: "How the superior olive compares timing and level between the ears.",
  },
  {
    id: "hair-cells",
    title: "Two kinds of hair cells in the cochlea",
    author: "Purves et al. · Neuroscience, 2nd ed. · 2001",
    url: "https://www.ncbi.nlm.nih.gov/books/NBK11122/",
    note: "Inner hair cells as the main output; outer hair cells as the cochlear amplifier.",
  },
  {
    id: "body-sensation",
    title: "The dorsal column–medial lemniscus system",
    author: "Purves et al. · Neuroscience, 2nd ed. · 2001",
    url: "https://www.ncbi.nlm.nih.gov/books/NBK11142/",
    note: "Fine touch and body position: medullary relay and crossing, VPL and somatosensory cortex.",
  },
  {
    id: "somatosensory-cortex",
    title: "Neuroanatomy, somatosensory cortex",
    author: "StatPearls · NCBI Bookshelf",
    url: "https://www.ncbi.nlm.nih.gov/books/NBK555915/",
    note: "Areas 3a, 3b, 1 and 2 and the body map.",
  },
  {
    id: "thalamus",
    title: "Thalamus plays a central role in ongoing cortical functioning",
    author: "Sherman · Nature Neuroscience · 2016",
    url: "https://www.nature.com/articles/nn.4269",
    note: "Driver and modulator inputs, cortical feedback and higher-order thalamus.",
  },
  {
    id: "switch",
    title: "A corticothalamic switch: controlling the thalamus with dynamic synapses",
    author: "Crandall, Cruikshank & Connors · Neuron · 2015",
    url: "https://doi.org/10.1016/j.neuron.2015.03.040",
    note: "Mouse somatosensory thalamus: layer 6 feedback suppresses or enhances relay cells depending on its firing rate.",
  },
  {
    id: "attention-networks",
    title: "Control of goal-directed and stimulus-driven attention in the brain",
    author: "Corbetta & Shulman · Nature Reviews Neuroscience · 2002",
    url: "https://doi.org/10.1038/nrn755",
    note: "The dorsal (goal-driven) and ventral (stimulus-driven) attention networks.",
  },
  {
    id: "salience",
    title: "Dissociable intrinsic connectivity networks for salience processing and executive control",
    author: "Seeley et al. · Journal of Neuroscience · 2007",
    url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC2680293/",
    note: "The insula–cingulate salience network, distinct from frontoparietal control networks.",
  },
  {
    id: "normalization",
    title: "The normalization model of attention",
    author: "Reynolds & Heeger · Neuron · 2009",
    url: "https://doi.org/10.1016/j.neuron.2009.01.002",
    note: "Attention as a gain change inside divisive normalization; the equation used in the Streams tab.",
  },
  {
    id: "pulvinar",
    title: "The pulvinar regulates information transmission between cortical areas based on attention demands",
    author: "Saalmann et al. · Science · 2012",
    url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC3714098/",
    note: "Macaque recordings: the pulvinar synchronizes visual areas according to attention.",
  },
  {
    id: "trn-selection",
    title: "Thalamic control of sensory selection in divided attention",
    author: "Wimmer et al. · Nature · 2015",
    url: "https://doi.org/10.1038/nature15398",
    note: "Mouse experiments: prefrontal cortex controls thalamic gain to suppress the sense being ignored.",
  },
  {
    id: "baseline",
    title: "Increased activity in human visual cortex during directed attention in the absence of visual stimulation",
    author: "Kastner et al. · Neuron · 1999",
    url: "https://doi.org/10.1016/S0896-6273(00)80734-5",
    note: "Human fMRI: attention raises visual-cortex activity before anything appears.",
  },
  {
    id: "language-streams",
    title: "The cortical organization of speech processing",
    author: "Hickok & Poeppel · Nature Reviews Neuroscience · 2007",
    url: "https://www.nature.com/articles/nrn2113",
    note: "The dual-stream model: ventral sound-to-meaning, dorsal sound-to-articulation.",
  },
  {
    id: "parallel-speech",
    title: "Parallel and distributed encoding of speech across human auditory cortex",
    author: "Hamilton, Oganian, Hall & Chang · Cell · 2021",
    url: "https://doi.org/10.1016/j.cell.2021.07.019",
    note: "Intracranial recordings: primary auditory cortex and superior temporal gyrus process speech in parallel.",
  },
  {
    id: "broca-timing",
    title: "Redefining the role of Broca’s area in speech",
    author: "Flinker et al. · PNAS · 2015",
    url: "https://doi.org/10.1073/pnas.1414491112",
    note: "Broca’s area is active before articulation and quiet during it.",
  },
  {
    id: "articulation",
    title: "Functional organization of human sensorimotor cortex for speech articulation",
    author: "Bouchard, Mesgarani, Johnson & Chang · Nature · 2013",
    url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC3606666/",
    note: "Maps of lips, jaw, tongue and larynx in ventral sensorimotor cortex.",
  },
  {
    id: "lgn-synapses",
    title: "Relative distribution of synapses in the A-laminae of the lateral geniculate nucleus of the cat",
    author: "Van Horn, Erişir & Sherman · Journal of Comparative Neurology · 2000",
    url: "https://pubmed.ncbi.nlm.nih.gov/10660881/",
    note: "Electron microscopy: about 7% of synapses on relay cells are retinal.",
  },
  {
    id: "ct-awake",
    title: "Dynamic corticothalamic modulation of the somatosensory thalamocortical circuit during wakefulness",
    author: "Dimwamwa et al. · Nature Communications · 2024",
    url: "https://doi.org/10.1038/s41467-024-47863-8",
    note: "Awake mice: layer 6 feedback suppresses or enhances the thalamus depending on firing rate and synchrony.",
  },
  {
    id: "attention-gain",
    title: "Effects of attention on orientation-tuning functions of single neurons in macaque cortical area V4",
    author: "McAdams & Maunsell · Journal of Neuroscience · 1999",
    url: "https://doi.org/10.1523/JNEUROSCI.19-01-00431.1999",
    note: "Attention scales responses: roughly 26% in V4 and 8% in V1.",
  },
  {
    id: "trn-basal-ganglia",
    title: "Prefrontal cortex regulates sensory filtering through a basal ganglia-to-thalamus pathway",
    author: "Nakajima, Schmitt & Halassa · Neuron · 2019",
    url: "https://doi.org/10.1016/j.neuron.2019.05.026",
    note: "Mice: the route from prefrontal cortex to the sensory TRN runs through the basal ganglia.",
  },
  {
    id: "speech-planning-debate",
    title: "Speech sequencing in the human precentral gyrus",
    author: "Liu, Zhao, Hullett & Chang · Nature Human Behaviour · 2025",
    url: "https://doi.org/10.1038/s41562-025-02250-1",
    note: "Evidence that a strip of precentral cortex sequences syllables; part of an open debate about Broca’s area.",
  },
  {
    id: "language-network",
    title: "The language network as a natural kind within the broader landscape of the human brain",
    author: "Fedorenko, Ivanova & Regev · Nature Reviews Neuroscience · 2024",
    url: "https://doi.org/10.1038/s41583-024-00802-4",
    note: "A left-lateralized, language-selective network distinct from general reasoning networks.",
  },
  {
    id: "atlas",
    title: "Z-Anatomy: geometry and credits",
    author: "Gauthier Kervyn · Lluís Vinent Juanico · contributors",
    url: "https://github.com/Z-Anatomy/Models-of-human-anatomy",
    note: "Source of the 3D anatomy. CC BY-SA 4.0; inner-ear meshes CC BY-NC-SA 4.0.",
  },
];
