import type { Source } from "./types";

export const sources: Source[] = [
  {
    id: "visual",
    title: "Central projections of retinal ganglion cells",
    author: "Purves et al. · Neuroscience, 2nd ed. · 2001",
    url: "https://www.ncbi.nlm.nih.gov/books/NBK11145/",
    note: "Retina → LGN → V1, partial crossing at the chiasm, and non-geniculate targets.",
  },
  {
    id: "visual-anatomy",
    title: "Neuroanatomy, visual pathway",
    author: "StatPearls · NCBI Bookshelf",
    url: "https://www.ncbi.nlm.nih.gov/books/NBK553189/",
    note: "Optic chiasm, visual-field organization, optic radiations and V1.",
  },
  {
    id: "photoreceptors",
    title: "Human photoreceptor topography",
    author: "Curcio et al. · Journal of Comparative Neurology · 1990",
    url: "https://doi.org/10.1002/cne.902920402",
    note: "Counts of rods and cones in human retinas.",
  },
  {
    id: "hubel-wiesel",
    title: "Receptive fields of single neurones in the cat’s striate cortex",
    author: "Hubel & Wiesel · Journal of Physiology · 1959",
    url: "https://doi.org/10.1113/jphysiol.1959.sp006308",
    note: "The discovery of orientation-selective neurons in primary visual cortex.",
  },
  {
    id: "parallel-pathways",
    title: "Parallel processing strategies of the primate visual system",
    author: "Nassi & Callaway · Nature Reviews Neuroscience · 2009",
    url: "https://doi.org/10.1038/nrn2619",
    note: "Magnocellular, parvocellular and koniocellular channels, and how they feed the cortical streams.",
  },
  {
    id: "two-streams",
    title: "Separate visual pathways for perception and action",
    author: "Goodale & Milner · Trends in Neurosciences · 1992",
    url: "https://doi.org/10.1016/0166-2236(92)90344-8",
    note: "The ventral stream for recognition and the dorsal stream for guiding action, including patient D.F.",
  },
  {
    id: "mt-review",
    title: "Structure and function of visual area MT",
    author: "Born & Bradley · Annual Review of Neuroscience · 2005",
    url: "https://doi.org/10.1146/annurev.neuro.26.041002.131052",
    note: "Direction and speed tuning in MT and its role in motion perception.",
  },
  {
    id: "object-recognition",
    title: "How does the brain solve visual object recognition?",
    author: "DiCarlo, Zoccolan & Rust · Neuron · 2012",
    url: "https://doi.org/10.1016/j.neuron.2012.01.010",
    note: "How the ventral stream builds object representations that tolerate changes in position, size and view.",
  },
  {
    id: "vtc-review",
    title: "The functional architecture of the ventral temporal cortex and its role in categorization",
    author: "Grill-Spector & Weiner · Nature Reviews Neuroscience · 2014",
    url: "https://doi.org/10.1038/nrn3747",
    note: "Where the face, place, body and word areas lie and how they relate to the anatomy.",
  },
  {
    id: "ear-anatomy",
    title: "Neuroanatomy, auditory pathway",
    author: "StatPearls · NCBI Bookshelf",
    url: "https://www.ncbi.nlm.nih.gov/books/NBK532311/",
    note: "Cochlea, ipsilateral cochlear nuclei, bilateral brainstem routes, midbrain and thalamic relays.",
  },
  {
    id: "auditory",
    title: "Integrating information from the two ears",
    author: "Purves et al. · Neuroscience, 2nd ed. · 2001",
    url: "https://www.ncbi.nlm.nih.gov/books/NBK10820/",
    note: "How the superior olive compares timing and level between the ears.",
  },
  {
    id: "hair-cells",
    title: "Two kinds of hair cells in the cochlea",
    author: "Purves et al. · Neuroscience, 2nd ed. · 2001",
    url: "https://www.ncbi.nlm.nih.gov/books/NBK11122/",
    note: "Inner hair cells as the main output; outer hair cells as the cochlear amplifier.",
  },
  {
    id: "body-sensation",
    title: "The dorsal column–medial lemniscus system",
    author: "Purves et al. · Neuroscience, 2nd ed. · 2001",
    url: "https://www.ncbi.nlm.nih.gov/books/NBK11142/",
    note: "Fine touch and body position: medullary relay and crossing, VPL and somatosensory cortex.",
  },
  {
    id: "somatosensory-cortex",
    title: "Neuroanatomy, somatosensory cortex",
    author: "StatPearls · NCBI Bookshelf",
    url: "https://www.ncbi.nlm.nih.gov/books/NBK555915/",
    note: "Areas 3a, 3b, 1 and 2 and the body map.",
  },
  {
    id: "thalamus",
    title: "Thalamus plays a central role in ongoing cortical functioning",
    author: "Sherman · Nature Neuroscience · 2016",
    url: "https://www.nature.com/articles/nn.4269",
    note: "Driver and modulator inputs, cortical feedback and higher-order thalamus.",
  },
  {
    id: "switch",
    title: "A corticothalamic switch: controlling the thalamus with dynamic synapses",
    author: "Crandall, Cruikshank & Connors · Neuron · 2015",
    url: "https://doi.org/10.1016/j.neuron.2015.03.040",
    note: "Mouse somatosensory thalamus: layer 6 feedback suppresses or enhances relay cells depending on its firing rate.",
  },
  {
    id: "attention-networks",
    title: "Control of goal-directed and stimulus-driven attention in the brain",
    author: "Corbetta & Shulman · Nature Reviews Neuroscience · 2002",
    url: "https://doi.org/10.1038/nrn755",
    note: "The dorsal (goal-driven) and ventral (stimulus-driven) attention networks.",
  },
  {
    id: "salience",
    title: "Dissociable intrinsic connectivity networks for salience processing and executive control",
    author: "Seeley et al. · Journal of Neuroscience · 2007",
    url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC2680293/",
    note: "The insula–cingulate salience network, distinct from frontoparietal control networks.",
  },
  {
    id: "normalization",
    title: "The normalization model of attention",
    author: "Reynolds & Heeger · Neuron · 2009",
    url: "https://doi.org/10.1016/j.neuron.2009.01.002",
    note: "Attention as a gain change inside divisive normalization; the equation used in the Streams tab.",
  },
  {
    id: "pulvinar",
    title: "The pulvinar regulates information transmission between cortical areas based on attention demands",
    author: "Saalmann et al. · Science · 2012",
    url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC3714098/",
    note: "Macaque recordings: the pulvinar synchronizes visual areas according to attention.",
  },
  {
    id: "trn-selection",
    title: "Thalamic control of sensory selection in divided attention",
    author: "Wimmer et al. · Nature · 2015",
    url: "https://doi.org/10.1038/nature15398",
    note: "Mouse experiments: prefrontal cortex controls thalamic gain to suppress the sense being ignored.",
  },
  {
    id: "baseline",
    title: "Increased activity in human visual cortex during directed attention in the absence of visual stimulation",
    author: "Kastner et al. · Neuron · 1999",
    url: "https://doi.org/10.1016/S0896-6273(00)80734-5",
    note: "Human fMRI: attention raises visual-cortex activity before anything appears.",
  },
  {
    id: "language-streams",
    title: "The cortical organization of speech processing",
    author: "Hickok & Poeppel · Nature Reviews Neuroscience · 2007",
    url: "https://www.nature.com/articles/nrn2113",
    note: "The dual-stream model: ventral sound-to-meaning, dorsal sound-to-articulation.",
  },
  {
    id: "parallel-speech",
    title: "Parallel and distributed encoding of speech across human auditory cortex",
    author: "Hamilton, Oganian, Hall & Chang · Cell · 2021",
    url: "https://doi.org/10.1016/j.cell.2021.07.019",
    note: "Intracranial recordings: primary auditory cortex and superior temporal gyrus process speech in parallel.",
  },
  {
    id: "broca-timing",
    title: "Redefining the role of Broca’s area in speech",
    author: "Flinker et al. · PNAS · 2015",
    url: "https://doi.org/10.1073/pnas.1414491112",
    note: "Broca’s area is active before articulation and quiet during it.",
  },
  {
    id: "articulation",
    title: "Functional organization of human sensorimotor cortex for speech articulation",
    author: "Bouchard, Mesgarani, Johnson & Chang · Nature · 2013",
    url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC3606666/",
    note: "Maps of lips, jaw, tongue and larynx in ventral sensorimotor cortex.",
  },
  {
    id: "lgn-synapses",
    title: "Relative distribution of synapses in the A-laminae of the lateral geniculate nucleus of the cat",
    author: "Van Horn, Erişir & Sherman · Journal of Comparative Neurology · 2000",
    url: "https://pubmed.ncbi.nlm.nih.gov/10660881/",
    note: "Electron microscopy: about 7% of synapses on relay cells are retinal.",
  },
  {
    id: "ct-awake",
    title: "Dynamic corticothalamic modulation of the somatosensory thalamocortical circuit during wakefulness",
    author: "Dimwamwa et al. · Nature Communications · 2024",
    url: "https://doi.org/10.1038/s41467-024-47863-8",
    note: "Awake mice: layer 6 feedback suppresses or enhances the thalamus depending on firing rate and synchrony.",
  },
  {
    id: "attention-gain",
    title: "Effects of attention on orientation-tuning functions of single neurons in macaque cortical area V4",
    author: "McAdams & Maunsell · Journal of Neuroscience · 1999",
    url: "https://doi.org/10.1523/JNEUROSCI.19-01-00431.1999",
    note: "Attention scales responses: roughly 26% in V4 and 8% in V1.",
  },
  {
    id: "trn-basal-ganglia",
    title: "Prefrontal cortex regulates sensory filtering through a basal ganglia-to-thalamus pathway",
    author: "Nakajima, Schmitt & Halassa · Neuron · 2019",
    url: "https://doi.org/10.1016/j.neuron.2019.05.026",
    note: "Mice: the route from prefrontal cortex to the sensory TRN runs through the basal ganglia.",
  },
  {
    id: "speech-planning-debate",
    title: "Speech sequencing in the human precentral gyrus",
    author: "Liu, Zhao, Hullett & Chang · Nature Human Behaviour · 2025",
    url: "https://doi.org/10.1038/s41562-025-02250-1",
    note: "Evidence that a strip of precentral cortex sequences syllables; part of an open debate about Broca’s area.",
  },
  {
    id: "language-network",
    title: "The language network as a natural kind within the broader landscape of the human brain",
    author: "Fedorenko, Ivanova & Regev · Nature Reviews Neuroscience · 2024",
    url: "https://doi.org/10.1038/s41583-024-00802-4",
    note: "A left-lateralized, language-selective network distinct from general reasoning networks.",
  },
  {
    id: "atlas",
    title: "Z-Anatomy: geometry and credits",
    author: "Gauthier Kervyn · Lluís Vinent Juanico · contributors",
    url: "https://github.com/Z-Anatomy/Models-of-human-anatomy",
    note: "Source of the 3D anatomy. CC BY-SA 4.0; inner-ear meshes CC BY-NC-SA 4.0.",
  },
  {
    id: "fef-v4",
    title: "Selective gating of visual signals by microstimulation of frontal cortex",
    author: "Moore & Armstrong · Nature · 2003",
    url: "https://doi.org/10.1038/nature01341",
    note: "Monkeys: frontal eye field stimulation too weak to move the eyes enhanced V4 responses at the matching location.",
  },
  {
    id: "fef-tms",
    title: "Concurrent TMS-fMRI and psychophysics reveal frontal influences on human retinotopic visual cortex",
    author: "Ruff et al. · Current Biology · 2006",
    url: "https://doi.org/10.1016/j.cub.2006.06.057",
    note: "Humans: TMS of the right frontal eye field changed activity in V1–V4 and perceived contrast.",
  },
  {
    id: "lip-priority",
    title: "Attention, intention, and priority in the parietal lobe",
    author: "Bisley & Goldberg · Annual Review of Neuroscience · 2010",
    url: "https://doi.org/10.1146/annurev-neuro-060909-152823",
    note: "Monkey area LIP as a priority map that guides both attention and eye movements.",
  },
  {
    id: "reorienting",
    title: "The reorienting system of the human brain: from environment to theory of mind",
    author: "Corbetta, Patel & Shulman · Neuron · 2008",
    url: "https://doi.org/10.1016/j.neuron.2008.04.017",
    note: "The right-lateralized ventral network (TPJ, ventral frontal cortex), its suppression during focused attention, and a proposed link to noradrenaline.",
  },
  {
    id: "network-taxonomy",
    title: "Towards a universal taxonomy of macro-scale functional human brain networks",
    author: "Uddin, Yeo & Spreng · Brain Topography · 2019",
    url: "https://doi.org/10.1007/s10548-019-00744-6",
    note: "How the salience, ventral attention and cingulo-opercular networks overlap, and why researchers name them differently.",
  },
  {
    id: "neglect-networks",
    title: "Spatial neglect and attention networks",
    author: "Corbetta & Shulman · Annual Review of Neuroscience · 2011",
    url: "https://doi.org/10.1146/annurev-neuro-061010-113731",
    note: "Neglect after right-hemisphere damage explained by disrupted ventral and dorsal attention networks.",
  },
  {
    id: "sc-attention",
    title: "Superior colliculus and visual spatial attention",
    author: "Krauzlis, Lovejoy & Zénon · Annual Review of Neuroscience · 2013",
    url: "https://doi.org/10.1146/annurev-neuro-062012-170249",
    note: "The superior colliculus in target selection and covert attention, and its routes to the cortex.",
  },
  {
    id: "sc-inactivation",
    title: "Inactivation of primate superior colliculus impairs covert selection of signals for perceptual judgments",
    author: "Lovejoy & Krauzlis · Nature Neuroscience · 2010",
    url: "https://doi.org/10.1038/nn.2470",
    note: "Monkeys: silencing the superior colliculus caused inattention to one part of the visual field when distractors competed.",
  },
  {
    id: "lc-adaptive-gain",
    title: "An integrative theory of locus coeruleus-norepinephrine function: adaptive gain and optimal performance",
    author: "Aston-Jones & Cohen · Annual Review of Neuroscience · 2005",
    url: "https://doi.org/10.1146/annurev.neuro.28.061604.135709",
    note: "Phasic and tonic modes of the locus coeruleus and their proposed roles in task engagement and exploration.",
  },
  {
    id: "ach-v1",
    title: "Acetylcholine contributes through muscarinic receptors to attentional modulation in V1",
    author: "Herrero et al. · Nature · 2008",
    url: "https://doi.org/10.1038/nature07141",
    note: "Monkeys: acetylcholine increased, and a muscarinic blocker reduced, attention effects on V1 neurons.",
  },
  {
    id: "neuromodulation",
    title: "Neuromodulation of attention",
    author: "Thiele & Bellgrove · Neuron · 2018",
    url: "https://doi.org/10.1016/j.neuron.2018.01.008",
    note: "Review of how acetylcholine, noradrenaline and dopamine shape attention in neurons and networks.",
  },
  {
    id: "pain-pathways",
    title: "Neuroanatomy of the pain system and of the pathways that modulate pain",
    author: "Willis & Westlund · Journal of Clinical Neurophysiology · 1997",
    url: "https://doi.org/10.1097/00004691-199701000-00002",
    note: "Where spinothalamic neurons lie in the dorsal horn, where their axons cross, and which thalamic nuclei they reach.",
  },
  {
    id: "s1-s2-review",
    title: "Neural basis of touch and proprioception in primate cortex",
    author: "Delhaye, Long & Bensmaia · Comprehensive Physiology · 2018",
    url: "https://doi.org/10.1002/cphy.c170033",
    note: "Areas 3a, 3b, 1 and 2, their body maps and inputs, and the second somatosensory area.",
  },
  {
    id: "s2-bilateral",
    title: "Activation of bilateral secondary somatosensory cortex with right hand touch stimulation: a meta-analysis of functional neuroimaging studies",
    author: "Lamp et al. · Frontiers in Neurology · 2019",
    url: "https://doi.org/10.3389/fneur.2018.01129",
    note: "Touch on one hand activates S2 in both hemispheres; source of the S2 marker coordinate.",
  },
  {
    id: "interoception",
    title: "How do you feel? Interoception: the sense of the physiological condition of the body",
    author: "Craig · Nature Reviews Neuroscience · 2002",
    url: "https://doi.org/10.1038/nrn894",
    note: "The lamina I spinothalamic pathway to the posterior insula as a representation of the body’s condition.",
  },
  {
    id: "cordotomy",
    title: "Spinal signalling of C-fiber mediated pleasant touch in humans",
    author: "Marshall et al. · eLife · 2019",
    url: "https://doi.org/10.7554/eLife.51642",
    note: "Cutting the spinothalamic tract in 19 patients removed pain, temperature and itch but left pleasant touch intact.",
  },
  {
    id: "pain-stimulation",
    title: "Stimulation of the human cortex and the experience of pain: Wilder Penfield’s observations revisited",
    author: "Mazzola, Isnard, Peyron & Mauguière · Brain · 2012",
    url: "https://doi.org/10.1093/brain/awr265",
    note: "Pain was evoked only from the posterior insula and medial parietal operculum in 4,160 cortical stimulations.",
  },
  {
    id: "pain-affect",
    title: "Pain affect encoded in human anterior cingulate but not somatosensory cortex",
    author: "Rainville et al. · Science · 1997",
    url: "https://doi.org/10.1126/science.277.5328.968",
    note: "Hypnosis changed pain unpleasantness and anterior cingulate activity without changing S1 activity.",
  },
  {
    id: "pain-matrix",
    title: "From the neuromatrix to the pain matrix (and back)",
    author: "Iannetti & Mouraux · Experimental Brain Research · 2010",
    url: "https://doi.org/10.1007/s00221-010-2340-1",
    note: "Most brain responses to brief painful stimuli are not specific to pain.",
  },
  {
    id: "auditory-cortex-streams",
    title: "Subdivisions of auditory cortex and processing streams in primates",
    author: "Kaas & Hackett · PNAS · 2000",
    url: "https://doi.org/10.1073/pnas.97.22.11793",
    note: "Monkey auditory cortex as core, belt and parabelt; the parabelt projects to temporal and frontal areas.",
  },
  {
    id: "auditory-what-where",
    title: "Mechanisms and streams for processing of “what” and “where” in auditory cortex",
    author: "Rauschecker & Tian · PNAS · 2000",
    url: "https://doi.org/10.1073/pnas.97.22.11800",
    note: "Monkey lateral belt: selectivity for complex sounds, with the front area specialized for call type and the back area for location.",
  },
  {
    id: "auditory-streams-review",
    title: "Maps and streams in the auditory cortex: nonhuman primates illuminate human speech processing",
    author: "Rauschecker & Scott · Nature Neuroscience · 2009",
    url: "https://doi.org/10.1038/nn.2331",
    note: "The two auditory streams in monkeys and humans, and why the back stream is not purely spatial.",
  },
  {
    id: "olivocochlear",
    title: "Olivocochlear efferents: anatomy, physiology, function, and the measurement of efferent effects in humans",
    author: "Guinan · Ear and Hearing · 2006",
    url: "https://doi.org/10.1097/01.aud.0000240507.83072.e7",
    note: "Medial olivocochlear fibres reduce outer hair cell amplification; how their effects are measured in humans with otoacoustic emissions.",
  },
  {
    id: "olivocochlear-behaviour",
    title: "Olivocochlear efferent effects on perception and behavior",
    author: "Lauer, Jimenez & Delano · Hearing Research · 2022",
    url: "https://doi.org/10.1016/j.heares.2021.108207",
    note: "Protection from noise is clear; roles in hearing in noise and in attention are established in animals but equivocal in humans.",
  },
  {
    id: "attention-cochlea",
    title: "Selective attention to visual stimuli reduces cochlear sensitivity in chinchillas",
    author: "Delano, Elgueda, Hamame & Robles · Journal of Neuroscience · 2007",
    url: "https://doi.org/10.1523/JNEUROSCI.3702-06.2007",
    note: "Chinchillas: cochlear responses to ignored sounds shrink during visual attention, probably through olivocochlear fibres.",
  },
  {
    id: "transthalamic",
    title: "A transthalamic pathway crucial for perception",
    author: "Mo, McKinnon & Sherman · Nature Communications · 2024",
    url: "https://doi.org/10.1038/s41467-024-50163-w",
    note: "Mice: silencing layer 5 input to higher-order touch thalamus impaired texture discrimination although direct cortical connections were intact.",
  },
  {
    id: "transthalamic-review",
    title: "Transthalamic pathways for cortical function",
    author: "Sherman & Usrey · Journal of Neuroscience · 2024",
    url: "https://doi.org/10.1523/JNEUROSCI.0909-24.2024",
    note: "Cortex → higher-order thalamus → cortex routes; most evidence is from mice, with anatomical support in cats and monkeys.",
  },
];
